// Code generated by ent, DO NOT EDIT.

package oidcsettings

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the oidcsettings type in the database.
	Label = "oidc_settings"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIssuer holds the string denoting the issuer field in the database.
	FieldIssuer = "issuer"
	// FieldAccessTokenTTLSeconds holds the string denoting the access_token_ttl_seconds field in the database.
	FieldAccessTokenTTLSeconds = "access_token_ttl_seconds"
	// FieldRefreshTokenTTLSeconds holds the string denoting the refresh_token_ttl_seconds field in the database.
	FieldRefreshTokenTTLSeconds = "refresh_token_ttl_seconds"
	// FieldIDTokenTTLSeconds holds the string denoting the id_token_ttl_seconds field in the database.
	FieldIDTokenTTLSeconds = "id_token_ttl_seconds"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the oidcsettings in the database.
	Table = "oidc_settings"
)

// Columns holds all SQL columns for oidcsettings fields.
var Columns = []string{
	FieldID,
	FieldIssuer,
	FieldAccessTokenTTLSeconds,
	FieldRefreshTokenTTLSeconds,
	FieldIDTokenTTLSeconds,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// IssuerValidator is a validator for the "issuer" field. It is called by the builders before save.
	IssuerValidator func(string) error
	// DefaultAccessTokenTTLSeconds holds the default value on creation for the "access_token_ttl_seconds" field.
	DefaultAccessTokenTTLSeconds int
	// AccessTokenTTLSecondsValidator is a validator for the "access_token_ttl_seconds" field. It is called by the builders before save.
	AccessTokenTTLSecondsValidator func(int) error
	// DefaultRefreshTokenTTLSeconds holds the default value on creation for the "refresh_token_ttl_seconds" field.
	DefaultRefreshTokenTTLSeconds int
	// RefreshTokenTTLSecondsValidator is a validator for the "refresh_token_ttl_seconds" field. It is called by the builders before save.
	RefreshTokenTTLSecondsValidator func(int) error
	// DefaultIDTokenTTLSeconds holds the default value on creation for the "id_token_ttl_seconds" field.
	DefaultIDTokenTTLSeconds int
	// IDTokenTTLSecondsValidator is a validator for the "id_token_ttl_seconds" field. It is called by the builders before save.
	IDTokenTTLSecondsValidator func(int) error
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the OIDCSettings queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByIssuer orders the results by the issuer field.
func ByIssuer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIssuer, opts...).ToFunc()
}

// ByAccessTokenTTLSeconds orders the results by the access_token_ttl_seconds field.
func ByAccessTokenTTLSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccessTokenTTLSeconds, opts...).ToFunc()
}

// ByRefreshTokenTTLSeconds orders the results by the refresh_token_ttl_seconds field.
func ByRefreshTokenTTLSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefreshTokenTTLSeconds, opts...).ToFunc()
}

// ByIDTokenTTLSeconds orders the results by the id_token_ttl_seconds field.
func ByIDTokenTTLSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIDTokenTTLSeconds, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
