// Code generated by ent, DO NOT EDIT.

package oidcsettings

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/andersonlmarchi/client-manager/services/configuration/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldContainsFold(FieldID, id))
}

// Issuer applies equality check predicate on the "issuer" field. It's identical to IssuerEQ.
func Issuer(v string) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldEQ(FieldIssuer, v))
}

// AccessTokenTTLSeconds applies equality check predicate on the "access_token_ttl_seconds" field. It's identical to AccessTokenTTLSecondsEQ.
func AccessTokenTTLSeconds(v int) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldEQ(FieldAccessTokenTTLSeconds, v))
}

// RefreshTokenTTLSeconds applies equality check predicate on the "refresh_token_ttl_seconds" field. It's identical to RefreshTokenTTLSecondsEQ.
func RefreshTokenTTLSeconds(v int) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldEQ(FieldRefreshTokenTTLSeconds, v))
}

// IDTokenTTLSeconds applies equality check predicate on the "id_token_ttl_seconds" field. It's identical to IDTokenTTLSecondsEQ.
func IDTokenTTLSeconds(v int) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldEQ(FieldIDTokenTTLSeconds, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldEQ(FieldUpdatedAt, v))
}

// IssuerEQ applies the EQ predicate on the "issuer" field.
func IssuerEQ(v string) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldEQ(FieldIssuer, v))
}

// IssuerNEQ applies the NEQ predicate on the "issuer" field.
func IssuerNEQ(v string) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldNEQ(FieldIssuer, v))
}

// IssuerIn applies the In predicate on the "issuer" field.
func IssuerIn(vs ...string) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldIn(FieldIssuer, vs...))
}

// IssuerNotIn applies the NotIn predicate on the "issuer" field.
func IssuerNotIn(vs ...string) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldNotIn(FieldIssuer, vs...))
}

// IssuerGT applies the GT predicate on the "issuer" field.
func IssuerGT(v string) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldGT(FieldIssuer, v))
}

// IssuerGTE applies the GTE predicate on the "issuer" field.
func IssuerGTE(v string) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldGTE(FieldIssuer, v))
}

// IssuerLT applies the LT predicate on the "issuer" field.
func IssuerLT(v string) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldLT(FieldIssuer, v))
}

// IssuerLTE applies the LTE predicate on the "issuer" field.
func IssuerLTE(v string) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldLTE(FieldIssuer, v))
}

// IssuerContains applies the Contains predicate on the "issuer" field.
func IssuerContains(v string) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldContains(FieldIssuer, v))
}

// IssuerHasPrefix applies the HasPrefix predicate on the "issuer" field.
func IssuerHasPrefix(v string) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldHasPrefix(FieldIssuer, v))
}

// IssuerHasSuffix applies the HasSuffix predicate on the "issuer" field.
func IssuerHasSuffix(v string) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldHasSuffix(FieldIssuer, v))
}

// IssuerEqualFold applies the EqualFold predicate on the "issuer" field.
func IssuerEqualFold(v string) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldEqualFold(FieldIssuer, v))
}

// IssuerContainsFold applies the ContainsFold predicate on the "issuer" field.
func IssuerContainsFold(v string) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldContainsFold(FieldIssuer, v))
}

// AccessTokenTTLSecondsEQ applies the EQ predicate on the "access_token_ttl_seconds" field.
func AccessTokenTTLSecondsEQ(v int) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldEQ(FieldAccessTokenTTLSeconds, v))
}

// AccessTokenTTLSecondsNEQ applies the NEQ predicate on the "access_token_ttl_seconds" field.
func AccessTokenTTLSecondsNEQ(v int) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldNEQ(FieldAccessTokenTTLSeconds, v))
}

// AccessTokenTTLSecondsIn applies the In predicate on the "access_token_ttl_seconds" field.
func AccessTokenTTLSecondsIn(vs ...int) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldIn(FieldAccessTokenTTLSeconds, vs...))
}

// AccessTokenTTLSecondsNotIn applies the NotIn predicate on the "access_token_ttl_seconds" field.
func AccessTokenTTLSecondsNotIn(vs ...int) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldNotIn(FieldAccessTokenTTLSeconds, vs...))
}

// AccessTokenTTLSecondsGT applies the GT predicate on the "access_token_ttl_seconds" field.
func AccessTokenTTLSecondsGT(v int) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldGT(FieldAccessTokenTTLSeconds, v))
}

// AccessTokenTTLSecondsGTE applies the GTE predicate on the "access_token_ttl_seconds" field.
func AccessTokenTTLSecondsGTE(v int) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldGTE(FieldAccessTokenTTLSeconds, v))
}

// AccessTokenTTLSecondsLT applies the LT predicate on the "access_token_ttl_seconds" field.
func AccessTokenTTLSecondsLT(v int) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldLT(FieldAccessTokenTTLSeconds, v))
}

// AccessTokenTTLSecondsLTE applies the LTE predicate on the "access_token_ttl_seconds" field.
func AccessTokenTTLSecondsLTE(v int) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldLTE(FieldAccessTokenTTLSeconds, v))
}

// RefreshTokenTTLSecondsEQ applies the EQ predicate on the "refresh_token_ttl_seconds" field.
func RefreshTokenTTLSecondsEQ(v int) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldEQ(FieldRefreshTokenTTLSeconds, v))
}

// RefreshTokenTTLSecondsNEQ applies the NEQ predicate on the "refresh_token_ttl_seconds" field.
func RefreshTokenTTLSecondsNEQ(v int) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldNEQ(FieldRefreshTokenTTLSeconds, v))
}

// RefreshTokenTTLSecondsIn applies the In predicate on the "refresh_token_ttl_seconds" field.
func RefreshTokenTTLSecondsIn(vs ...int) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldIn(FieldRefreshTokenTTLSeconds, vs...))
}

// RefreshTokenTTLSecondsNotIn applies the NotIn predicate on the "refresh_token_ttl_seconds" field.
func RefreshTokenTTLSecondsNotIn(vs ...int) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldNotIn(FieldRefreshTokenTTLSeconds, vs...))
}

// RefreshTokenTTLSecondsGT applies the GT predicate on the "refresh_token_ttl_seconds" field.
func RefreshTokenTTLSecondsGT(v int) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldGT(FieldRefreshTokenTTLSeconds, v))
}

// RefreshTokenTTLSecondsGTE applies the GTE predicate on the "refresh_token_ttl_seconds" field.
func RefreshTokenTTLSecondsGTE(v int) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldGTE(FieldRefreshTokenTTLSeconds, v))
}

// RefreshTokenTTLSecondsLT applies the LT predicate on the "refresh_token_ttl_seconds" field.
func RefreshTokenTTLSecondsLT(v int) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldLT(FieldRefreshTokenTTLSeconds, v))
}

// RefreshTokenTTLSecondsLTE applies the LTE predicate on the "refresh_token_ttl_seconds" field.
func RefreshTokenTTLSecondsLTE(v int) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldLTE(FieldRefreshTokenTTLSeconds, v))
}

// IDTokenTTLSecondsEQ applies the EQ predicate on the "id_token_ttl_seconds" field.
func IDTokenTTLSecondsEQ(v int) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldEQ(FieldIDTokenTTLSeconds, v))
}

// IDTokenTTLSecondsNEQ applies the NEQ predicate on the "id_token_ttl_seconds" field.
func IDTokenTTLSecondsNEQ(v int) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldNEQ(FieldIDTokenTTLSeconds, v))
}

// IDTokenTTLSecondsIn applies the In predicate on the "id_token_ttl_seconds" field.
func IDTokenTTLSecondsIn(vs ...int) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldIn(FieldIDTokenTTLSeconds, vs...))
}

// IDTokenTTLSecondsNotIn applies the NotIn predicate on the "id_token_ttl_seconds" field.
func IDTokenTTLSecondsNotIn(vs ...int) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldNotIn(FieldIDTokenTTLSeconds, vs...))
}

// IDTokenTTLSecondsGT applies the GT predicate on the "id_token_ttl_seconds" field.
func IDTokenTTLSecondsGT(v int) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldGT(FieldIDTokenTTLSeconds, v))
}

// IDTokenTTLSecondsGTE applies the GTE predicate on the "id_token_ttl_seconds" field.
func IDTokenTTLSecondsGTE(v int) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldGTE(FieldIDTokenTTLSeconds, v))
}

// IDTokenTTLSecondsLT applies the LT predicate on the "id_token_ttl_seconds" field.
func IDTokenTTLSecondsLT(v int) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldLT(FieldIDTokenTTLSeconds, v))
}

// IDTokenTTLSecondsLTE applies the LTE predicate on the "id_token_ttl_seconds" field.
func IDTokenTTLSecondsLTE(v int) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldLTE(FieldIDTokenTTLSeconds, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.OIDCSettings) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.OIDCSettings) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.OIDCSettings) predicate.OIDCSettings {
	return predicate.OIDCSettings(sql.NotPredicates(p))
}
