// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/andersonlmarchi/client-manager/services/identity/ent/credential"
	"github.com/andersonlmarchi/client-manager/services/identity/ent/user"
)

// CredentialCreate is the builder for creating a Credential entity.
type CredentialCreate struct {
	config
	mutation *CredentialMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetPasswordHash sets the "password_hash" field.
func (_c *CredentialCreate) SetPasswordHash(v string) *CredentialCreate {
	_c.mutation.SetPasswordHash(v)
	return _c
}

// SetAlgorithm sets the "algorithm" field.
func (_c *CredentialCreate) SetAlgorithm(v string) *CredentialCreate {
	_c.mutation.SetAlgorithm(v)
	return _c
}

// SetNillableAlgorithm sets the "algorithm" field if the given value is not nil.
func (_c *CredentialCreate) SetNillableAlgorithm(v *string) *CredentialCreate {
	if v != nil {
		_c.SetAlgorithm(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CredentialCreate) SetCreatedAt(v time.Time) *CredentialCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CredentialCreate) SetNillableCreatedAt(v *time.Time) *CredentialCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CredentialCreate) SetUpdatedAt(v time.Time) *CredentialCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CredentialCreate) SetNillableUpdatedAt(v *time.Time) *CredentialCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CredentialCreate) SetID(v string) *CredentialCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *CredentialCreate) SetUserID(id string) *CredentialCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *CredentialCreate) SetUser(v *User) *CredentialCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the CredentialMutation object of the builder.
func (_c *CredentialCreate) Mutation() *CredentialMutation {
	return _c.mutation
}

// Save creates the Credential in the database.
func (_c *CredentialCreate) Save(ctx context.Context) (*Credential, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CredentialCreate) SaveX(ctx context.Context) *Credential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CredentialCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CredentialCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *CredentialCreate) defaults() {
	if _, ok := _c.mutation.Algorithm(); !ok {
		v := credential.DefaultAlgorithm
		_c.mutation.SetAlgorithm(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := credential.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := credential.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CredentialCreate) check() error {
	if _, ok := _c.mutation.PasswordHash(); !ok {
		return &ValidationError{Name: "password_hash", err: errors.New(`ent: missing required field "Credential.password_hash"`)}
	}
	if v, ok := _c.mutation.PasswordHash(); ok {
		if err := credential.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "Credential.password_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Algorithm(); !ok {
		return &ValidationError{Name: "algorithm", err: errors.New(`ent: missing required field "Credential.algorithm"`)}
	}
	if v, ok := _c.mutation.Algorithm(); ok {
		if err := credential.AlgorithmValidator(v); err != nil {
			return &ValidationError{Name: "algorithm", err: fmt.Errorf(`ent: validator failed for field "Credential.algorithm": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Credential.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Credential.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Credential.user"`)}
	}
	return nil
}

func (_c *CredentialCreate) sqlSave(ctx context.Context) (*Credential, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Credential.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CredentialCreate) createSpec() (*Credential, *sqlgraph.CreateSpec) {
	var (
		_node = &Credential{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(credential.Table, sqlgraph.NewFieldSpec(credential.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.PasswordHash(); ok {
		_spec.SetField(credential.FieldPasswordHash, field.TypeString, value)
		_node.PasswordHash = value
	}
	if value, ok := _c.mutation.Algorithm(); ok {
		_spec.SetField(credential.FieldAlgorithm, field.TypeString, value)
		_node.Algorithm = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(credential.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(credential.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   credential.UserTable,
			Columns: []string{credential.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_credential = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Credential.Create().
//		SetPasswordHash(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CredentialUpsert) {
//			SetPasswordHash(v+v).
//		}).
//		Exec(ctx)
func (_c *CredentialCreate) OnConflict(opts ...sql.ConflictOption) *CredentialUpsertOne {
	_c.conflict = opts
	return &CredentialUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Credential.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CredentialCreate) OnConflictColumns(columns ...string) *CredentialUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CredentialUpsertOne{
		create: _c,
	}
}

type (
	// CredentialUpsertOne is the builder for "upsert"-ing
	//  one Credential node.
	CredentialUpsertOne struct {
		create *CredentialCreate
	}

	// CredentialUpsert is the "OnConflict" setter.
	CredentialUpsert struct {
		*sql.UpdateSet
	}
)

// SetPasswordHash sets the "password_hash" field.
func (u *CredentialUpsert) SetPasswordHash(v string) *CredentialUpsert {
	u.Set(credential.FieldPasswordHash, v)
	return u
}

// UpdatePasswordHash sets the "password_hash" field to the value that was provided on create.
func (u *CredentialUpsert) UpdatePasswordHash() *CredentialUpsert {
	u.SetExcluded(credential.FieldPasswordHash)
	return u
}

// SetAlgorithm sets the "algorithm" field.
func (u *CredentialUpsert) SetAlgorithm(v string) *CredentialUpsert {
	u.Set(credential.FieldAlgorithm, v)
	return u
}

// UpdateAlgorithm sets the "algorithm" field to the value that was provided on create.
func (u *CredentialUpsert) UpdateAlgorithm() *CredentialUpsert {
	u.SetExcluded(credential.FieldAlgorithm)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CredentialUpsert) SetUpdatedAt(v time.Time) *CredentialUpsert {
	u.Set(credential.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CredentialUpsert) UpdateUpdatedAt() *CredentialUpsert {
	u.SetExcluded(credential.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Credential.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(credential.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CredentialUpsertOne) UpdateNewValues() *CredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(credential.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(credential.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Credential.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *CredentialUpsertOne) Ignore() *CredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CredentialUpsertOne) DoNothing() *CredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CredentialCreate.OnConflict
// documentation for more info.
func (u *CredentialUpsertOne) Update(set func(*CredentialUpsert)) *CredentialUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CredentialUpsert{UpdateSet: update})
	}))
	return u
}

// SetPasswordHash sets the "password_hash" field.
func (u *CredentialUpsertOne) SetPasswordHash(v string) *CredentialUpsertOne {
	return u.Update(func(s *CredentialUpsert) {
		s.SetPasswordHash(v)
	})
}

// UpdatePasswordHash sets the "password_hash" field to the value that was provided on create.
func (u *CredentialUpsertOne) UpdatePasswordHash() *CredentialUpsertOne {
	return u.Update(func(s *CredentialUpsert) {
		s.UpdatePasswordHash()
	})
}

// SetAlgorithm sets the "algorithm" field.
func (u *CredentialUpsertOne) SetAlgorithm(v string) *CredentialUpsertOne {
	return u.Update(func(s *CredentialUpsert) {
		s.SetAlgorithm(v)
	})
}

// UpdateAlgorithm sets the "algorithm" field to the value that was provided on create.
func (u *CredentialUpsertOne) UpdateAlgorithm() *CredentialUpsertOne {
	return u.Update(func(s *CredentialUpsert) {
		s.UpdateAlgorithm()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CredentialUpsertOne) SetUpdatedAt(v time.Time) *CredentialUpsertOne {
	return u.Update(func(s *CredentialUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CredentialUpsertOne) UpdateUpdatedAt() *CredentialUpsertOne {
	return u.Update(func(s *CredentialUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CredentialUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CredentialCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CredentialUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *CredentialUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: CredentialUpsertOne.ID is not supported by MySQL driver. Use CredentialUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *CredentialUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// CredentialCreateBulk is the builder for creating many Credential entities in bulk.
type CredentialCreateBulk struct {
	config
	err      error
	builders []*CredentialCreate
	conflict []sql.ConflictOption
}

// Save creates the Credential entities in the database.
func (_c *CredentialCreateBulk) Save(ctx context.Context) ([]*Credential, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Credential, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CredentialMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CredentialCreateBulk) SaveX(ctx context.Context) []*Credential {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CredentialCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CredentialCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Credential.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.CredentialUpsert) {
//			SetPasswordHash(v+v).
//		}).
//		Exec(ctx)
func (_c *CredentialCreateBulk) OnConflict(opts ...sql.ConflictOption) *CredentialUpsertBulk {
	_c.conflict = opts
	return &CredentialUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Credential.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *CredentialCreateBulk) OnConflictColumns(columns ...string) *CredentialUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &CredentialUpsertBulk{
		create: _c,
	}
}

// CredentialUpsertBulk is the builder for "upsert"-ing
// a bulk of Credential nodes.
type CredentialUpsertBulk struct {
	create *CredentialCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Credential.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(credential.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *CredentialUpsertBulk) UpdateNewValues() *CredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(credential.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(credential.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Credential.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *CredentialUpsertBulk) Ignore() *CredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *CredentialUpsertBulk) DoNothing() *CredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the CredentialCreateBulk.OnConflict
// documentation for more info.
func (u *CredentialUpsertBulk) Update(set func(*CredentialUpsert)) *CredentialUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&CredentialUpsert{UpdateSet: update})
	}))
	return u
}

// SetPasswordHash sets the "password_hash" field.
func (u *CredentialUpsertBulk) SetPasswordHash(v string) *CredentialUpsertBulk {
	return u.Update(func(s *CredentialUpsert) {
		s.SetPasswordHash(v)
	})
}

// UpdatePasswordHash sets the "password_hash" field to the value that was provided on create.
func (u *CredentialUpsertBulk) UpdatePasswordHash() *CredentialUpsertBulk {
	return u.Update(func(s *CredentialUpsert) {
		s.UpdatePasswordHash()
	})
}

// SetAlgorithm sets the "algorithm" field.
func (u *CredentialUpsertBulk) SetAlgorithm(v string) *CredentialUpsertBulk {
	return u.Update(func(s *CredentialUpsert) {
		s.SetAlgorithm(v)
	})
}

// UpdateAlgorithm sets the "algorithm" field to the value that was provided on create.
func (u *CredentialUpsertBulk) UpdateAlgorithm() *CredentialUpsertBulk {
	return u.Update(func(s *CredentialUpsert) {
		s.UpdateAlgorithm()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *CredentialUpsertBulk) SetUpdatedAt(v time.Time) *CredentialUpsertBulk {
	return u.Update(func(s *CredentialUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *CredentialUpsertBulk) UpdateUpdatedAt() *CredentialUpsertBulk {
	return u.Update(func(s *CredentialUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *CredentialUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the CredentialCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for CredentialCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *CredentialUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
