// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/andersonlmarchi/client-manager/services/identity/ent/credential"
	"github.com/andersonlmarchi/client-manager/services/identity/ent/schema"
	"github.com/andersonlmarchi/client-manager/services/identity/ent/session"
	"github.com/andersonlmarchi/client-manager/services/identity/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	credentialFields := schema.Credential{}.Fields()
	_ = credentialFields
	// credentialDescPasswordHash is the schema descriptor for password_hash field.
	credentialDescPasswordHash := credentialFields[1].Descriptor()
	// credential.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	credential.PasswordHashValidator = credentialDescPasswordHash.Validators[0].(func(string) error)
	// credentialDescAlgorithm is the schema descriptor for algorithm field.
	credentialDescAlgorithm := credentialFields[2].Descriptor()
	// credential.DefaultAlgorithm holds the default value on creation for the algorithm field.
	credential.DefaultAlgorithm = credentialDescAlgorithm.Default.(string)
	// credential.AlgorithmValidator is a validator for the "algorithm" field. It is called by the builders before save.
	credential.AlgorithmValidator = credentialDescAlgorithm.Validators[0].(func(string) error)
	// credentialDescCreatedAt is the schema descriptor for created_at field.
	credentialDescCreatedAt := credentialFields[3].Descriptor()
	// credential.DefaultCreatedAt holds the default value on creation for the created_at field.
	credential.DefaultCreatedAt = credentialDescCreatedAt.Default.(func() time.Time)
	// credentialDescUpdatedAt is the schema descriptor for updated_at field.
	credentialDescUpdatedAt := credentialFields[4].Descriptor()
	// credential.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	credential.DefaultUpdatedAt = credentialDescUpdatedAt.Default.(func() time.Time)
	// credential.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	credential.UpdateDefaultUpdatedAt = credentialDescUpdatedAt.UpdateDefault.(func() time.Time)
	sessionFields := schema.Session{}.Fields()
	_ = sessionFields
	// sessionDescTokenHash is the schema descriptor for token_hash field.
	sessionDescTokenHash := sessionFields[1].Descriptor()
	// session.TokenHashValidator is a validator for the "token_hash" field. It is called by the builders before save.
	session.TokenHashValidator = sessionDescTokenHash.Validators[0].(func(string) error)
	// sessionDescCreatedAt is the schema descriptor for created_at field.
	sessionDescCreatedAt := sessionFields[6].Descriptor()
	// session.DefaultCreatedAt holds the default value on creation for the created_at field.
	session.DefaultCreatedAt = sessionDescCreatedAt.Default.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[4].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
}
