// Code generated by ent, DO NOT EDIT.

package passwordpolicy

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/andersonlmarchi/client-manager/services/configuration/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldContainsFold(FieldID, id))
}

// MinLength applies equality check predicate on the "min_length" field. It's identical to MinLengthEQ.
func MinLength(v int) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldEQ(FieldMinLength, v))
}

// RequireUpper applies equality check predicate on the "require_upper" field. It's identical to RequireUpperEQ.
func RequireUpper(v bool) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldEQ(FieldRequireUpper, v))
}

// RequireLower applies equality check predicate on the "require_lower" field. It's identical to RequireLowerEQ.
func RequireLower(v bool) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldEQ(FieldRequireLower, v))
}

// RequireNumber applies equality check predicate on the "require_number" field. It's identical to RequireNumberEQ.
func RequireNumber(v bool) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldEQ(FieldRequireNumber, v))
}

// RequireSymbol applies equality check predicate on the "require_symbol" field. It's identical to RequireSymbolEQ.
func RequireSymbol(v bool) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldEQ(FieldRequireSymbol, v))
}

// MaxAgeDays applies equality check predicate on the "max_age_days" field. It's identical to MaxAgeDaysEQ.
func MaxAgeDays(v int) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldEQ(FieldMaxAgeDays, v))
}

// HistoryCount applies equality check predicate on the "history_count" field. It's identical to HistoryCountEQ.
func HistoryCount(v int) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldEQ(FieldHistoryCount, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldEQ(FieldUpdatedAt, v))
}

// MinLengthEQ applies the EQ predicate on the "min_length" field.
func MinLengthEQ(v int) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldEQ(FieldMinLength, v))
}

// MinLengthNEQ applies the NEQ predicate on the "min_length" field.
func MinLengthNEQ(v int) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldNEQ(FieldMinLength, v))
}

// MinLengthIn applies the In predicate on the "min_length" field.
func MinLengthIn(vs ...int) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldIn(FieldMinLength, vs...))
}

// MinLengthNotIn applies the NotIn predicate on the "min_length" field.
func MinLengthNotIn(vs ...int) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldNotIn(FieldMinLength, vs...))
}

// MinLengthGT applies the GT predicate on the "min_length" field.
func MinLengthGT(v int) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldGT(FieldMinLength, v))
}

// MinLengthGTE applies the GTE predicate on the "min_length" field.
func MinLengthGTE(v int) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldGTE(FieldMinLength, v))
}

// MinLengthLT applies the LT predicate on the "min_length" field.
func MinLengthLT(v int) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldLT(FieldMinLength, v))
}

// MinLengthLTE applies the LTE predicate on the "min_length" field.
func MinLengthLTE(v int) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldLTE(FieldMinLength, v))
}

// RequireUpperEQ applies the EQ predicate on the "require_upper" field.
func RequireUpperEQ(v bool) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldEQ(FieldRequireUpper, v))
}

// RequireUpperNEQ applies the NEQ predicate on the "require_upper" field.
func RequireUpperNEQ(v bool) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldNEQ(FieldRequireUpper, v))
}

// RequireLowerEQ applies the EQ predicate on the "require_lower" field.
func RequireLowerEQ(v bool) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldEQ(FieldRequireLower, v))
}

// RequireLowerNEQ applies the NEQ predicate on the "require_lower" field.
func RequireLowerNEQ(v bool) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldNEQ(FieldRequireLower, v))
}

// RequireNumberEQ applies the EQ predicate on the "require_number" field.
func RequireNumberEQ(v bool) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldEQ(FieldRequireNumber, v))
}

// RequireNumberNEQ applies the NEQ predicate on the "require_number" field.
func RequireNumberNEQ(v bool) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldNEQ(FieldRequireNumber, v))
}

// RequireSymbolEQ applies the EQ predicate on the "require_symbol" field.
func RequireSymbolEQ(v bool) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldEQ(FieldRequireSymbol, v))
}

// RequireSymbolNEQ applies the NEQ predicate on the "require_symbol" field.
func RequireSymbolNEQ(v bool) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldNEQ(FieldRequireSymbol, v))
}

// MaxAgeDaysEQ applies the EQ predicate on the "max_age_days" field.
func MaxAgeDaysEQ(v int) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldEQ(FieldMaxAgeDays, v))
}

// MaxAgeDaysNEQ applies the NEQ predicate on the "max_age_days" field.
func MaxAgeDaysNEQ(v int) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldNEQ(FieldMaxAgeDays, v))
}

// MaxAgeDaysIn applies the In predicate on the "max_age_days" field.
func MaxAgeDaysIn(vs ...int) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldIn(FieldMaxAgeDays, vs...))
}

// MaxAgeDaysNotIn applies the NotIn predicate on the "max_age_days" field.
func MaxAgeDaysNotIn(vs ...int) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldNotIn(FieldMaxAgeDays, vs...))
}

// MaxAgeDaysGT applies the GT predicate on the "max_age_days" field.
func MaxAgeDaysGT(v int) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldGT(FieldMaxAgeDays, v))
}

// MaxAgeDaysGTE applies the GTE predicate on the "max_age_days" field.
func MaxAgeDaysGTE(v int) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldGTE(FieldMaxAgeDays, v))
}

// MaxAgeDaysLT applies the LT predicate on the "max_age_days" field.
func MaxAgeDaysLT(v int) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldLT(FieldMaxAgeDays, v))
}

// MaxAgeDaysLTE applies the LTE predicate on the "max_age_days" field.
func MaxAgeDaysLTE(v int) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldLTE(FieldMaxAgeDays, v))
}

// HistoryCountEQ applies the EQ predicate on the "history_count" field.
func HistoryCountEQ(v int) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldEQ(FieldHistoryCount, v))
}

// HistoryCountNEQ applies the NEQ predicate on the "history_count" field.
func HistoryCountNEQ(v int) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldNEQ(FieldHistoryCount, v))
}

// HistoryCountIn applies the In predicate on the "history_count" field.
func HistoryCountIn(vs ...int) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldIn(FieldHistoryCount, vs...))
}

// HistoryCountNotIn applies the NotIn predicate on the "history_count" field.
func HistoryCountNotIn(vs ...int) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldNotIn(FieldHistoryCount, vs...))
}

// HistoryCountGT applies the GT predicate on the "history_count" field.
func HistoryCountGT(v int) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldGT(FieldHistoryCount, v))
}

// HistoryCountGTE applies the GTE predicate on the "history_count" field.
func HistoryCountGTE(v int) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldGTE(FieldHistoryCount, v))
}

// HistoryCountLT applies the LT predicate on the "history_count" field.
func HistoryCountLT(v int) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldLT(FieldHistoryCount, v))
}

// HistoryCountLTE applies the LTE predicate on the "history_count" field.
func HistoryCountLTE(v int) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldLTE(FieldHistoryCount, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PasswordPolicy) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PasswordPolicy) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PasswordPolicy) predicate.PasswordPolicy {
	return predicate.PasswordPolicy(sql.NotPredicates(p))
}
