// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// BrandingSettings is the predicate function for brandingsettings builders.
type BrandingSettings func(*sql.Selector)

// OIDCSettings is the predicate function for oidcsettings builders.
type OIDCSettings func(*sql.Selector)

// PasswordPolicy is the predicate function for passwordpolicy builders.
type PasswordPolicy func(*sql.Selector)

// RateLimitSettings is the predicate function for ratelimitsettings builders.
type RateLimitSettings func(*sql.Selector)
