// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/andersonlmarchi/client-manager/services/configuration/ent/brandingsettings"
)

// BrandingSettingsCreate is the builder for creating a BrandingSettings entity.
type BrandingSettingsCreate struct {
	config
	mutation *BrandingSettingsMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAppName sets the "app_name" field.
func (_c *BrandingSettingsCreate) SetAppName(v string) *BrandingSettingsCreate {
	_c.mutation.SetAppName(v)
	return _c
}

// SetLogoURL sets the "logo_url" field.
func (_c *BrandingSettingsCreate) SetLogoURL(v string) *BrandingSettingsCreate {
	_c.mutation.SetLogoURL(v)
	return _c
}

// SetNillableLogoURL sets the "logo_url" field if the given value is not nil.
func (_c *BrandingSettingsCreate) SetNillableLogoURL(v *string) *BrandingSettingsCreate {
	if v != nil {
		_c.SetLogoURL(*v)
	}
	return _c
}

// SetPrimaryColor sets the "primary_color" field.
func (_c *BrandingSettingsCreate) SetPrimaryColor(v string) *BrandingSettingsCreate {
	_c.mutation.SetPrimaryColor(v)
	return _c
}

// SetNillablePrimaryColor sets the "primary_color" field if the given value is not nil.
func (_c *BrandingSettingsCreate) SetNillablePrimaryColor(v *string) *BrandingSettingsCreate {
	if v != nil {
		_c.SetPrimaryColor(*v)
	}
	return _c
}

// SetSupportEmail sets the "support_email" field.
func (_c *BrandingSettingsCreate) SetSupportEmail(v string) *BrandingSettingsCreate {
	_c.mutation.SetSupportEmail(v)
	return _c
}

// SetNillableSupportEmail sets the "support_email" field if the given value is not nil.
func (_c *BrandingSettingsCreate) SetNillableSupportEmail(v *string) *BrandingSettingsCreate {
	if v != nil {
		_c.SetSupportEmail(*v)
	}
	return _c
}

// SetSMTPHostRef sets the "smtp_host_ref" field.
func (_c *BrandingSettingsCreate) SetSMTPHostRef(v string) *BrandingSettingsCreate {
	_c.mutation.SetSMTPHostRef(v)
	return _c
}

// SetNillableSMTPHostRef sets the "smtp_host_ref" field if the given value is not nil.
func (_c *BrandingSettingsCreate) SetNillableSMTPHostRef(v *string) *BrandingSettingsCreate {
	if v != nil {
		_c.SetSMTPHostRef(*v)
	}
	return _c
}

// SetSMTPPortRef sets the "smtp_port_ref" field.
func (_c *BrandingSettingsCreate) SetSMTPPortRef(v string) *BrandingSettingsCreate {
	_c.mutation.SetSMTPPortRef(v)
	return _c
}

// SetNillableSMTPPortRef sets the "smtp_port_ref" field if the given value is not nil.
func (_c *BrandingSettingsCreate) SetNillableSMTPPortRef(v *string) *BrandingSettingsCreate {
	if v != nil {
		_c.SetSMTPPortRef(*v)
	}
	return _c
}

// SetSMTPUserRef sets the "smtp_user_ref" field.
func (_c *BrandingSettingsCreate) SetSMTPUserRef(v string) *BrandingSettingsCreate {
	_c.mutation.SetSMTPUserRef(v)
	return _c
}

// SetNillableSMTPUserRef sets the "smtp_user_ref" field if the given value is not nil.
func (_c *BrandingSettingsCreate) SetNillableSMTPUserRef(v *string) *BrandingSettingsCreate {
	if v != nil {
		_c.SetSMTPUserRef(*v)
	}
	return _c
}

// SetFromEmail sets the "from_email" field.
func (_c *BrandingSettingsCreate) SetFromEmail(v string) *BrandingSettingsCreate {
	_c.mutation.SetFromEmail(v)
	return _c
}

// SetNillableFromEmail sets the "from_email" field if the given value is not nil.
func (_c *BrandingSettingsCreate) SetNillableFromEmail(v *string) *BrandingSettingsCreate {
	if v != nil {
		_c.SetFromEmail(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *BrandingSettingsCreate) SetUpdatedAt(v time.Time) *BrandingSettingsCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *BrandingSettingsCreate) SetNillableUpdatedAt(v *time.Time) *BrandingSettingsCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *BrandingSettingsCreate) SetID(v string) *BrandingSettingsCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the BrandingSettingsMutation object of the builder.
func (_c *BrandingSettingsCreate) Mutation() *BrandingSettingsMutation {
	return _c.mutation
}

// Save creates the BrandingSettings in the database.
func (_c *BrandingSettingsCreate) Save(ctx context.Context) (*BrandingSettings, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *BrandingSettingsCreate) SaveX(ctx context.Context) *BrandingSettings {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BrandingSettingsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BrandingSettingsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *BrandingSettingsCreate) defaults() {
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := brandingsettings.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *BrandingSettingsCreate) check() error {
	if _, ok := _c.mutation.AppName(); !ok {
		return &ValidationError{Name: "app_name", err: errors.New(`ent: missing required field "BrandingSettings.app_name"`)}
	}
	if v, ok := _c.mutation.AppName(); ok {
		if err := brandingsettings.AppNameValidator(v); err != nil {
			return &ValidationError{Name: "app_name", err: fmt.Errorf(`ent: validator failed for field "BrandingSettings.app_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "BrandingSettings.updated_at"`)}
	}
	return nil
}

func (_c *BrandingSettingsCreate) sqlSave(ctx context.Context) (*BrandingSettings, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected BrandingSettings.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *BrandingSettingsCreate) createSpec() (*BrandingSettings, *sqlgraph.CreateSpec) {
	var (
		_node = &BrandingSettings{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(brandingsettings.Table, sqlgraph.NewFieldSpec(brandingsettings.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.AppName(); ok {
		_spec.SetField(brandingsettings.FieldAppName, field.TypeString, value)
		_node.AppName = value
	}
	if value, ok := _c.mutation.LogoURL(); ok {
		_spec.SetField(brandingsettings.FieldLogoURL, field.TypeString, value)
		_node.LogoURL = &value
	}
	if value, ok := _c.mutation.PrimaryColor(); ok {
		_spec.SetField(brandingsettings.FieldPrimaryColor, field.TypeString, value)
		_node.PrimaryColor = &value
	}
	if value, ok := _c.mutation.SupportEmail(); ok {
		_spec.SetField(brandingsettings.FieldSupportEmail, field.TypeString, value)
		_node.SupportEmail = &value
	}
	if value, ok := _c.mutation.SMTPHostRef(); ok {
		_spec.SetField(brandingsettings.FieldSMTPHostRef, field.TypeString, value)
		_node.SMTPHostRef = &value
	}
	if value, ok := _c.mutation.SMTPPortRef(); ok {
		_spec.SetField(brandingsettings.FieldSMTPPortRef, field.TypeString, value)
		_node.SMTPPortRef = &value
	}
	if value, ok := _c.mutation.SMTPUserRef(); ok {
		_spec.SetField(brandingsettings.FieldSMTPUserRef, field.TypeString, value)
		_node.SMTPUserRef = &value
	}
	if value, ok := _c.mutation.FromEmail(); ok {
		_spec.SetField(brandingsettings.FieldFromEmail, field.TypeString, value)
		_node.FromEmail = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(brandingsettings.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BrandingSettings.Create().
//		SetAppName(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BrandingSettingsUpsert) {
//			SetAppName(v+v).
//		}).
//		Exec(ctx)
func (_c *BrandingSettingsCreate) OnConflict(opts ...sql.ConflictOption) *BrandingSettingsUpsertOne {
	_c.conflict = opts
	return &BrandingSettingsUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BrandingSettings.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BrandingSettingsCreate) OnConflictColumns(columns ...string) *BrandingSettingsUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BrandingSettingsUpsertOne{
		create: _c,
	}
}

type (
	// BrandingSettingsUpsertOne is the builder for "upsert"-ing
	//  one BrandingSettings node.
	BrandingSettingsUpsertOne struct {
		create *BrandingSettingsCreate
	}

	// BrandingSettingsUpsert is the "OnConflict" setter.
	BrandingSettingsUpsert struct {
		*sql.UpdateSet
	}
)

// SetAppName sets the "app_name" field.
func (u *BrandingSettingsUpsert) SetAppName(v string) *BrandingSettingsUpsert {
	u.Set(brandingsettings.FieldAppName, v)
	return u
}

// UpdateAppName sets the "app_name" field to the value that was provided on create.
func (u *BrandingSettingsUpsert) UpdateAppName() *BrandingSettingsUpsert {
	u.SetExcluded(brandingsettings.FieldAppName)
	return u
}

// SetLogoURL sets the "logo_url" field.
func (u *BrandingSettingsUpsert) SetLogoURL(v string) *BrandingSettingsUpsert {
	u.Set(brandingsettings.FieldLogoURL, v)
	return u
}

// UpdateLogoURL sets the "logo_url" field to the value that was provided on create.
func (u *BrandingSettingsUpsert) UpdateLogoURL() *BrandingSettingsUpsert {
	u.SetExcluded(brandingsettings.FieldLogoURL)
	return u
}

// ClearLogoURL clears the value of the "logo_url" field.
func (u *BrandingSettingsUpsert) ClearLogoURL() *BrandingSettingsUpsert {
	u.SetNull(brandingsettings.FieldLogoURL)
	return u
}

// SetPrimaryColor sets the "primary_color" field.
func (u *BrandingSettingsUpsert) SetPrimaryColor(v string) *BrandingSettingsUpsert {
	u.Set(brandingsettings.FieldPrimaryColor, v)
	return u
}

// UpdatePrimaryColor sets the "primary_color" field to the value that was provided on create.
func (u *BrandingSettingsUpsert) UpdatePrimaryColor() *BrandingSettingsUpsert {
	u.SetExcluded(brandingsettings.FieldPrimaryColor)
	return u
}

// ClearPrimaryColor clears the value of the "primary_color" field.
func (u *BrandingSettingsUpsert) ClearPrimaryColor() *BrandingSettingsUpsert {
	u.SetNull(brandingsettings.FieldPrimaryColor)
	return u
}

// SetSupportEmail sets the "support_email" field.
func (u *BrandingSettingsUpsert) SetSupportEmail(v string) *BrandingSettingsUpsert {
	u.Set(brandingsettings.FieldSupportEmail, v)
	return u
}

// UpdateSupportEmail sets the "support_email" field to the value that was provided on create.
func (u *BrandingSettingsUpsert) UpdateSupportEmail() *BrandingSettingsUpsert {
	u.SetExcluded(brandingsettings.FieldSupportEmail)
	return u
}

// ClearSupportEmail clears the value of the "support_email" field.
func (u *BrandingSettingsUpsert) ClearSupportEmail() *BrandingSettingsUpsert {
	u.SetNull(brandingsettings.FieldSupportEmail)
	return u
}

// SetSMTPHostRef sets the "smtp_host_ref" field.
func (u *BrandingSettingsUpsert) SetSMTPHostRef(v string) *BrandingSettingsUpsert {
	u.Set(brandingsettings.FieldSMTPHostRef, v)
	return u
}

// UpdateSMTPHostRef sets the "smtp_host_ref" field to the value that was provided on create.
func (u *BrandingSettingsUpsert) UpdateSMTPHostRef() *BrandingSettingsUpsert {
	u.SetExcluded(brandingsettings.FieldSMTPHostRef)
	return u
}

// ClearSMTPHostRef clears the value of the "smtp_host_ref" field.
func (u *BrandingSettingsUpsert) ClearSMTPHostRef() *BrandingSettingsUpsert {
	u.SetNull(brandingsettings.FieldSMTPHostRef)
	return u
}

// SetSMTPPortRef sets the "smtp_port_ref" field.
func (u *BrandingSettingsUpsert) SetSMTPPortRef(v string) *BrandingSettingsUpsert {
	u.Set(brandingsettings.FieldSMTPPortRef, v)
	return u
}

// UpdateSMTPPortRef sets the "smtp_port_ref" field to the value that was provided on create.
func (u *BrandingSettingsUpsert) UpdateSMTPPortRef() *BrandingSettingsUpsert {
	u.SetExcluded(brandingsettings.FieldSMTPPortRef)
	return u
}

// ClearSMTPPortRef clears the value of the "smtp_port_ref" field.
func (u *BrandingSettingsUpsert) ClearSMTPPortRef() *BrandingSettingsUpsert {
	u.SetNull(brandingsettings.FieldSMTPPortRef)
	return u
}

// SetSMTPUserRef sets the "smtp_user_ref" field.
func (u *BrandingSettingsUpsert) SetSMTPUserRef(v string) *BrandingSettingsUpsert {
	u.Set(brandingsettings.FieldSMTPUserRef, v)
	return u
}

// UpdateSMTPUserRef sets the "smtp_user_ref" field to the value that was provided on create.
func (u *BrandingSettingsUpsert) UpdateSMTPUserRef() *BrandingSettingsUpsert {
	u.SetExcluded(brandingsettings.FieldSMTPUserRef)
	return u
}

// ClearSMTPUserRef clears the value of the "smtp_user_ref" field.
func (u *BrandingSettingsUpsert) ClearSMTPUserRef() *BrandingSettingsUpsert {
	u.SetNull(brandingsettings.FieldSMTPUserRef)
	return u
}

// SetFromEmail sets the "from_email" field.
func (u *BrandingSettingsUpsert) SetFromEmail(v string) *BrandingSettingsUpsert {
	u.Set(brandingsettings.FieldFromEmail, v)
	return u
}

// UpdateFromEmail sets the "from_email" field to the value that was provided on create.
func (u *BrandingSettingsUpsert) UpdateFromEmail() *BrandingSettingsUpsert {
	u.SetExcluded(brandingsettings.FieldFromEmail)
	return u
}

// ClearFromEmail clears the value of the "from_email" field.
func (u *BrandingSettingsUpsert) ClearFromEmail() *BrandingSettingsUpsert {
	u.SetNull(brandingsettings.FieldFromEmail)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BrandingSettingsUpsert) SetUpdatedAt(v time.Time) *BrandingSettingsUpsert {
	u.Set(brandingsettings.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BrandingSettingsUpsert) UpdateUpdatedAt() *BrandingSettingsUpsert {
	u.SetExcluded(brandingsettings.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.BrandingSettings.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(brandingsettings.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BrandingSettingsUpsertOne) UpdateNewValues() *BrandingSettingsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(brandingsettings.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BrandingSettings.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *BrandingSettingsUpsertOne) Ignore() *BrandingSettingsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BrandingSettingsUpsertOne) DoNothing() *BrandingSettingsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BrandingSettingsCreate.OnConflict
// documentation for more info.
func (u *BrandingSettingsUpsertOne) Update(set func(*BrandingSettingsUpsert)) *BrandingSettingsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BrandingSettingsUpsert{UpdateSet: update})
	}))
	return u
}

// SetAppName sets the "app_name" field.
func (u *BrandingSettingsUpsertOne) SetAppName(v string) *BrandingSettingsUpsertOne {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.SetAppName(v)
	})
}

// UpdateAppName sets the "app_name" field to the value that was provided on create.
func (u *BrandingSettingsUpsertOne) UpdateAppName() *BrandingSettingsUpsertOne {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.UpdateAppName()
	})
}

// SetLogoURL sets the "logo_url" field.
func (u *BrandingSettingsUpsertOne) SetLogoURL(v string) *BrandingSettingsUpsertOne {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.SetLogoURL(v)
	})
}

// UpdateLogoURL sets the "logo_url" field to the value that was provided on create.
func (u *BrandingSettingsUpsertOne) UpdateLogoURL() *BrandingSettingsUpsertOne {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.UpdateLogoURL()
	})
}

// ClearLogoURL clears the value of the "logo_url" field.
func (u *BrandingSettingsUpsertOne) ClearLogoURL() *BrandingSettingsUpsertOne {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.ClearLogoURL()
	})
}

// SetPrimaryColor sets the "primary_color" field.
func (u *BrandingSettingsUpsertOne) SetPrimaryColor(v string) *BrandingSettingsUpsertOne {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.SetPrimaryColor(v)
	})
}

// UpdatePrimaryColor sets the "primary_color" field to the value that was provided on create.
func (u *BrandingSettingsUpsertOne) UpdatePrimaryColor() *BrandingSettingsUpsertOne {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.UpdatePrimaryColor()
	})
}

// ClearPrimaryColor clears the value of the "primary_color" field.
func (u *BrandingSettingsUpsertOne) ClearPrimaryColor() *BrandingSettingsUpsertOne {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.ClearPrimaryColor()
	})
}

// SetSupportEmail sets the "support_email" field.
func (u *BrandingSettingsUpsertOne) SetSupportEmail(v string) *BrandingSettingsUpsertOne {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.SetSupportEmail(v)
	})
}

// UpdateSupportEmail sets the "support_email" field to the value that was provided on create.
func (u *BrandingSettingsUpsertOne) UpdateSupportEmail() *BrandingSettingsUpsertOne {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.UpdateSupportEmail()
	})
}

// ClearSupportEmail clears the value of the "support_email" field.
func (u *BrandingSettingsUpsertOne) ClearSupportEmail() *BrandingSettingsUpsertOne {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.ClearSupportEmail()
	})
}

// SetSMTPHostRef sets the "smtp_host_ref" field.
func (u *BrandingSettingsUpsertOne) SetSMTPHostRef(v string) *BrandingSettingsUpsertOne {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.SetSMTPHostRef(v)
	})
}

// UpdateSMTPHostRef sets the "smtp_host_ref" field to the value that was provided on create.
func (u *BrandingSettingsUpsertOne) UpdateSMTPHostRef() *BrandingSettingsUpsertOne {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.UpdateSMTPHostRef()
	})
}

// ClearSMTPHostRef clears the value of the "smtp_host_ref" field.
func (u *BrandingSettingsUpsertOne) ClearSMTPHostRef() *BrandingSettingsUpsertOne {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.ClearSMTPHostRef()
	})
}

// SetSMTPPortRef sets the "smtp_port_ref" field.
func (u *BrandingSettingsUpsertOne) SetSMTPPortRef(v string) *BrandingSettingsUpsertOne {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.SetSMTPPortRef(v)
	})
}

// UpdateSMTPPortRef sets the "smtp_port_ref" field to the value that was provided on create.
func (u *BrandingSettingsUpsertOne) UpdateSMTPPortRef() *BrandingSettingsUpsertOne {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.UpdateSMTPPortRef()
	})
}

// ClearSMTPPortRef clears the value of the "smtp_port_ref" field.
func (u *BrandingSettingsUpsertOne) ClearSMTPPortRef() *BrandingSettingsUpsertOne {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.ClearSMTPPortRef()
	})
}

// SetSMTPUserRef sets the "smtp_user_ref" field.
func (u *BrandingSettingsUpsertOne) SetSMTPUserRef(v string) *BrandingSettingsUpsertOne {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.SetSMTPUserRef(v)
	})
}

// UpdateSMTPUserRef sets the "smtp_user_ref" field to the value that was provided on create.
func (u *BrandingSettingsUpsertOne) UpdateSMTPUserRef() *BrandingSettingsUpsertOne {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.UpdateSMTPUserRef()
	})
}

// ClearSMTPUserRef clears the value of the "smtp_user_ref" field.
func (u *BrandingSettingsUpsertOne) ClearSMTPUserRef() *BrandingSettingsUpsertOne {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.ClearSMTPUserRef()
	})
}

// SetFromEmail sets the "from_email" field.
func (u *BrandingSettingsUpsertOne) SetFromEmail(v string) *BrandingSettingsUpsertOne {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.SetFromEmail(v)
	})
}

// UpdateFromEmail sets the "from_email" field to the value that was provided on create.
func (u *BrandingSettingsUpsertOne) UpdateFromEmail() *BrandingSettingsUpsertOne {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.UpdateFromEmail()
	})
}

// ClearFromEmail clears the value of the "from_email" field.
func (u *BrandingSettingsUpsertOne) ClearFromEmail() *BrandingSettingsUpsertOne {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.ClearFromEmail()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BrandingSettingsUpsertOne) SetUpdatedAt(v time.Time) *BrandingSettingsUpsertOne {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BrandingSettingsUpsertOne) UpdateUpdatedAt() *BrandingSettingsUpsertOne {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *BrandingSettingsUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BrandingSettingsCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BrandingSettingsUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *BrandingSettingsUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: BrandingSettingsUpsertOne.ID is not supported by MySQL driver. Use BrandingSettingsUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *BrandingSettingsUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// BrandingSettingsCreateBulk is the builder for creating many BrandingSettings entities in bulk.
type BrandingSettingsCreateBulk struct {
	config
	err      error
	builders []*BrandingSettingsCreate
	conflict []sql.ConflictOption
}

// Save creates the BrandingSettings entities in the database.
func (_c *BrandingSettingsCreateBulk) Save(ctx context.Context) ([]*BrandingSettings, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*BrandingSettings, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BrandingSettingsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *BrandingSettingsCreateBulk) SaveX(ctx context.Context) []*BrandingSettings {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *BrandingSettingsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *BrandingSettingsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.BrandingSettings.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.BrandingSettingsUpsert) {
//			SetAppName(v+v).
//		}).
//		Exec(ctx)
func (_c *BrandingSettingsCreateBulk) OnConflict(opts ...sql.ConflictOption) *BrandingSettingsUpsertBulk {
	_c.conflict = opts
	return &BrandingSettingsUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.BrandingSettings.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *BrandingSettingsCreateBulk) OnConflictColumns(columns ...string) *BrandingSettingsUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &BrandingSettingsUpsertBulk{
		create: _c,
	}
}

// BrandingSettingsUpsertBulk is the builder for "upsert"-ing
// a bulk of BrandingSettings nodes.
type BrandingSettingsUpsertBulk struct {
	create *BrandingSettingsCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.BrandingSettings.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(brandingsettings.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *BrandingSettingsUpsertBulk) UpdateNewValues() *BrandingSettingsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(brandingsettings.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.BrandingSettings.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *BrandingSettingsUpsertBulk) Ignore() *BrandingSettingsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *BrandingSettingsUpsertBulk) DoNothing() *BrandingSettingsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the BrandingSettingsCreateBulk.OnConflict
// documentation for more info.
func (u *BrandingSettingsUpsertBulk) Update(set func(*BrandingSettingsUpsert)) *BrandingSettingsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&BrandingSettingsUpsert{UpdateSet: update})
	}))
	return u
}

// SetAppName sets the "app_name" field.
func (u *BrandingSettingsUpsertBulk) SetAppName(v string) *BrandingSettingsUpsertBulk {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.SetAppName(v)
	})
}

// UpdateAppName sets the "app_name" field to the value that was provided on create.
func (u *BrandingSettingsUpsertBulk) UpdateAppName() *BrandingSettingsUpsertBulk {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.UpdateAppName()
	})
}

// SetLogoURL sets the "logo_url" field.
func (u *BrandingSettingsUpsertBulk) SetLogoURL(v string) *BrandingSettingsUpsertBulk {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.SetLogoURL(v)
	})
}

// UpdateLogoURL sets the "logo_url" field to the value that was provided on create.
func (u *BrandingSettingsUpsertBulk) UpdateLogoURL() *BrandingSettingsUpsertBulk {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.UpdateLogoURL()
	})
}

// ClearLogoURL clears the value of the "logo_url" field.
func (u *BrandingSettingsUpsertBulk) ClearLogoURL() *BrandingSettingsUpsertBulk {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.ClearLogoURL()
	})
}

// SetPrimaryColor sets the "primary_color" field.
func (u *BrandingSettingsUpsertBulk) SetPrimaryColor(v string) *BrandingSettingsUpsertBulk {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.SetPrimaryColor(v)
	})
}

// UpdatePrimaryColor sets the "primary_color" field to the value that was provided on create.
func (u *BrandingSettingsUpsertBulk) UpdatePrimaryColor() *BrandingSettingsUpsertBulk {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.UpdatePrimaryColor()
	})
}

// ClearPrimaryColor clears the value of the "primary_color" field.
func (u *BrandingSettingsUpsertBulk) ClearPrimaryColor() *BrandingSettingsUpsertBulk {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.ClearPrimaryColor()
	})
}

// SetSupportEmail sets the "support_email" field.
func (u *BrandingSettingsUpsertBulk) SetSupportEmail(v string) *BrandingSettingsUpsertBulk {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.SetSupportEmail(v)
	})
}

// UpdateSupportEmail sets the "support_email" field to the value that was provided on create.
func (u *BrandingSettingsUpsertBulk) UpdateSupportEmail() *BrandingSettingsUpsertBulk {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.UpdateSupportEmail()
	})
}

// ClearSupportEmail clears the value of the "support_email" field.
func (u *BrandingSettingsUpsertBulk) ClearSupportEmail() *BrandingSettingsUpsertBulk {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.ClearSupportEmail()
	})
}

// SetSMTPHostRef sets the "smtp_host_ref" field.
func (u *BrandingSettingsUpsertBulk) SetSMTPHostRef(v string) *BrandingSettingsUpsertBulk {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.SetSMTPHostRef(v)
	})
}

// UpdateSMTPHostRef sets the "smtp_host_ref" field to the value that was provided on create.
func (u *BrandingSettingsUpsertBulk) UpdateSMTPHostRef() *BrandingSettingsUpsertBulk {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.UpdateSMTPHostRef()
	})
}

// ClearSMTPHostRef clears the value of the "smtp_host_ref" field.
func (u *BrandingSettingsUpsertBulk) ClearSMTPHostRef() *BrandingSettingsUpsertBulk {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.ClearSMTPHostRef()
	})
}

// SetSMTPPortRef sets the "smtp_port_ref" field.
func (u *BrandingSettingsUpsertBulk) SetSMTPPortRef(v string) *BrandingSettingsUpsertBulk {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.SetSMTPPortRef(v)
	})
}

// UpdateSMTPPortRef sets the "smtp_port_ref" field to the value that was provided on create.
func (u *BrandingSettingsUpsertBulk) UpdateSMTPPortRef() *BrandingSettingsUpsertBulk {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.UpdateSMTPPortRef()
	})
}

// ClearSMTPPortRef clears the value of the "smtp_port_ref" field.
func (u *BrandingSettingsUpsertBulk) ClearSMTPPortRef() *BrandingSettingsUpsertBulk {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.ClearSMTPPortRef()
	})
}

// SetSMTPUserRef sets the "smtp_user_ref" field.
func (u *BrandingSettingsUpsertBulk) SetSMTPUserRef(v string) *BrandingSettingsUpsertBulk {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.SetSMTPUserRef(v)
	})
}

// UpdateSMTPUserRef sets the "smtp_user_ref" field to the value that was provided on create.
func (u *BrandingSettingsUpsertBulk) UpdateSMTPUserRef() *BrandingSettingsUpsertBulk {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.UpdateSMTPUserRef()
	})
}

// ClearSMTPUserRef clears the value of the "smtp_user_ref" field.
func (u *BrandingSettingsUpsertBulk) ClearSMTPUserRef() *BrandingSettingsUpsertBulk {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.ClearSMTPUserRef()
	})
}

// SetFromEmail sets the "from_email" field.
func (u *BrandingSettingsUpsertBulk) SetFromEmail(v string) *BrandingSettingsUpsertBulk {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.SetFromEmail(v)
	})
}

// UpdateFromEmail sets the "from_email" field to the value that was provided on create.
func (u *BrandingSettingsUpsertBulk) UpdateFromEmail() *BrandingSettingsUpsertBulk {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.UpdateFromEmail()
	})
}

// ClearFromEmail clears the value of the "from_email" field.
func (u *BrandingSettingsUpsertBulk) ClearFromEmail() *BrandingSettingsUpsertBulk {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.ClearFromEmail()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *BrandingSettingsUpsertBulk) SetUpdatedAt(v time.Time) *BrandingSettingsUpsertBulk {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *BrandingSettingsUpsertBulk) UpdateUpdatedAt() *BrandingSettingsUpsertBulk {
	return u.Update(func(s *BrandingSettingsUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *BrandingSettingsUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the BrandingSettingsCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for BrandingSettingsCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *BrandingSettingsUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
