// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"log"
	"reflect"

	"github.com/andersonlmarchi/client-manager/services/configuration/ent/migrate"

	"entgo.io/ent"
	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"github.com/andersonlmarchi/client-manager/services/configuration/ent/brandingsettings"
	"github.com/andersonlmarchi/client-manager/services/configuration/ent/oidcsettings"
	"github.com/andersonlmarchi/client-manager/services/configuration/ent/passwordpolicy"
	"github.com/andersonlmarchi/client-manager/services/configuration/ent/ratelimitsettings"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// BrandingSettings is the client for interacting with the BrandingSettings builders.
	BrandingSettings *BrandingSettingsClient
	// OIDCSettings is the client for interacting with the OIDCSettings builders.
	OIDCSettings *OIDCSettingsClient
	// PasswordPolicy is the client for interacting with the PasswordPolicy builders.
	PasswordPolicy *PasswordPolicyClient
	// RateLimitSettings is the client for interacting with the RateLimitSettings builders.
	RateLimitSettings *RateLimitSettingsClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	client := &Client{config: newConfig(opts...)}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.BrandingSettings = NewBrandingSettingsClient(c.config)
	c.OIDCSettings = NewOIDCSettingsClient(c.config)
	c.PasswordPolicy = NewPasswordPolicyClient(c.config)
	c.RateLimitSettings = NewRateLimitSettingsClient(c.config)
}

type (
	// config is the configuration for the client and its builder.
	config struct {
		// driver used for executing database requests.
		driver dialect.Driver
		// debug enable a debug logging.
		debug bool
		// log used for logging on debug mode.
		log func(...any)
		// hooks to execute on mutations.
		hooks *hooks
		// interceptors to execute on queries.
		inters *inters
	}
	// Option function to configure the client.
	Option func(*config)
)

// newConfig creates a new config for the client.
func newConfig(opts ...Option) config {
	cfg := config{log: log.Println, hooks: &hooks{}, inters: &inters{}}
	cfg.options(opts...)
	return cfg
}

// options applies the options on the config object.
func (c *config) options(opts ...Option) {
	for _, opt := range opts {
		opt(c)
	}
	if c.debug {
		c.driver = dialect.Debug(c.driver, c.log)
	}
}

// Debug enables debug logging on the ent.Driver.
func Debug() Option {
	return func(c *config) {
		c.debug = true
	}
}

// Log sets the logging function for debug mode.
func Log(fn func(...any)) Option {
	return func(c *config) {
		c.log = fn
	}
}

// Driver configures the client driver.
func Driver(driver dialect.Driver) Option {
	return func(c *config) {
		c.driver = driver
	}
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// ErrTxStarted is returned when trying to start a new transaction from a transactional client.
var ErrTxStarted = errors.New("ent: cannot start a transaction within a transaction")

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, ErrTxStarted
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:               ctx,
		config:            cfg,
		BrandingSettings:  NewBrandingSettingsClient(cfg),
		OIDCSettings:      NewOIDCSettingsClient(cfg),
		PasswordPolicy:    NewPasswordPolicyClient(cfg),
		RateLimitSettings: NewRateLimitSettingsClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, errors.New("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:               ctx,
		config:            cfg,
		BrandingSettings:  NewBrandingSettingsClient(cfg),
		OIDCSettings:      NewOIDCSettingsClient(cfg),
		PasswordPolicy:    NewPasswordPolicyClient(cfg),
		RateLimitSettings: NewRateLimitSettingsClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		BrandingSettings.
//		Query().
//		Count(ctx)
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.BrandingSettings.Use(hooks...)
	c.OIDCSettings.Use(hooks...)
	c.PasswordPolicy.Use(hooks...)
	c.RateLimitSettings.Use(hooks...)
}

// Intercept adds the query interceptors to all the entity clients.
// In order to add interceptors to a specific client, call: `client.Node.Intercept(...)`.
func (c *Client) Intercept(interceptors ...Interceptor) {
	c.BrandingSettings.Intercept(interceptors...)
	c.OIDCSettings.Intercept(interceptors...)
	c.PasswordPolicy.Intercept(interceptors...)
	c.RateLimitSettings.Intercept(interceptors...)
}

// Mutate implements the ent.Mutator interface.
func (c *Client) Mutate(ctx context.Context, m Mutation) (Value, error) {
	switch m := m.(type) {
	case *BrandingSettingsMutation:
		return c.BrandingSettings.mutate(ctx, m)
	case *OIDCSettingsMutation:
		return c.OIDCSettings.mutate(ctx, m)
	case *PasswordPolicyMutation:
		return c.PasswordPolicy.mutate(ctx, m)
	case *RateLimitSettingsMutation:
		return c.RateLimitSettings.mutate(ctx, m)
	default:
		return nil, fmt.Errorf("ent: unknown mutation type %T", m)
	}
}

// BrandingSettingsClient is a client for the BrandingSettings schema.
type BrandingSettingsClient struct {
	config
}

// NewBrandingSettingsClient returns a client for the BrandingSettings from the given config.
func NewBrandingSettingsClient(c config) *BrandingSettingsClient {
	return &BrandingSettingsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `brandingsettings.Hooks(f(g(h())))`.
func (c *BrandingSettingsClient) Use(hooks ...Hook) {
	c.hooks.BrandingSettings = append(c.hooks.BrandingSettings, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `brandingsettings.Intercept(f(g(h())))`.
func (c *BrandingSettingsClient) Intercept(interceptors ...Interceptor) {
	c.inters.BrandingSettings = append(c.inters.BrandingSettings, interceptors...)
}

// Create returns a builder for creating a BrandingSettings entity.
func (c *BrandingSettingsClient) Create() *BrandingSettingsCreate {
	mutation := newBrandingSettingsMutation(c.config, OpCreate)
	return &BrandingSettingsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of BrandingSettings entities.
func (c *BrandingSettingsClient) CreateBulk(builders ...*BrandingSettingsCreate) *BrandingSettingsCreateBulk {
	return &BrandingSettingsCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *BrandingSettingsClient) MapCreateBulk(slice any, setFunc func(*BrandingSettingsCreate, int)) *BrandingSettingsCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &BrandingSettingsCreateBulk{err: fmt.Errorf("calling to BrandingSettingsClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*BrandingSettingsCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &BrandingSettingsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for BrandingSettings.
func (c *BrandingSettingsClient) Update() *BrandingSettingsUpdate {
	mutation := newBrandingSettingsMutation(c.config, OpUpdate)
	return &BrandingSettingsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *BrandingSettingsClient) UpdateOne(_m *BrandingSettings) *BrandingSettingsUpdateOne {
	mutation := newBrandingSettingsMutation(c.config, OpUpdateOne, withBrandingSettings(_m))
	return &BrandingSettingsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *BrandingSettingsClient) UpdateOneID(id string) *BrandingSettingsUpdateOne {
	mutation := newBrandingSettingsMutation(c.config, OpUpdateOne, withBrandingSettingsID(id))
	return &BrandingSettingsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for BrandingSettings.
func (c *BrandingSettingsClient) Delete() *BrandingSettingsDelete {
	mutation := newBrandingSettingsMutation(c.config, OpDelete)
	return &BrandingSettingsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *BrandingSettingsClient) DeleteOne(_m *BrandingSettings) *BrandingSettingsDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *BrandingSettingsClient) DeleteOneID(id string) *BrandingSettingsDeleteOne {
	builder := c.Delete().Where(brandingsettings.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &BrandingSettingsDeleteOne{builder}
}

// Query returns a query builder for BrandingSettings.
func (c *BrandingSettingsClient) Query() *BrandingSettingsQuery {
	return &BrandingSettingsQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeBrandingSettings},
		inters: c.Interceptors(),
	}
}

// Get returns a BrandingSettings entity by its id.
func (c *BrandingSettingsClient) Get(ctx context.Context, id string) (*BrandingSettings, error) {
	return c.Query().Where(brandingsettings.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *BrandingSettingsClient) GetX(ctx context.Context, id string) *BrandingSettings {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *BrandingSettingsClient) Hooks() []Hook {
	return c.hooks.BrandingSettings
}

// Interceptors returns the client interceptors.
func (c *BrandingSettingsClient) Interceptors() []Interceptor {
	return c.inters.BrandingSettings
}

func (c *BrandingSettingsClient) mutate(ctx context.Context, m *BrandingSettingsMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&BrandingSettingsCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&BrandingSettingsUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&BrandingSettingsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&BrandingSettingsDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown BrandingSettings mutation op: %q", m.Op())
	}
}

// OIDCSettingsClient is a client for the OIDCSettings schema.
type OIDCSettingsClient struct {
	config
}

// NewOIDCSettingsClient returns a client for the OIDCSettings from the given config.
func NewOIDCSettingsClient(c config) *OIDCSettingsClient {
	return &OIDCSettingsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `oidcsettings.Hooks(f(g(h())))`.
func (c *OIDCSettingsClient) Use(hooks ...Hook) {
	c.hooks.OIDCSettings = append(c.hooks.OIDCSettings, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `oidcsettings.Intercept(f(g(h())))`.
func (c *OIDCSettingsClient) Intercept(interceptors ...Interceptor) {
	c.inters.OIDCSettings = append(c.inters.OIDCSettings, interceptors...)
}

// Create returns a builder for creating a OIDCSettings entity.
func (c *OIDCSettingsClient) Create() *OIDCSettingsCreate {
	mutation := newOIDCSettingsMutation(c.config, OpCreate)
	return &OIDCSettingsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of OIDCSettings entities.
func (c *OIDCSettingsClient) CreateBulk(builders ...*OIDCSettingsCreate) *OIDCSettingsCreateBulk {
	return &OIDCSettingsCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *OIDCSettingsClient) MapCreateBulk(slice any, setFunc func(*OIDCSettingsCreate, int)) *OIDCSettingsCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &OIDCSettingsCreateBulk{err: fmt.Errorf("calling to OIDCSettingsClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*OIDCSettingsCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &OIDCSettingsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for OIDCSettings.
func (c *OIDCSettingsClient) Update() *OIDCSettingsUpdate {
	mutation := newOIDCSettingsMutation(c.config, OpUpdate)
	return &OIDCSettingsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *OIDCSettingsClient) UpdateOne(_m *OIDCSettings) *OIDCSettingsUpdateOne {
	mutation := newOIDCSettingsMutation(c.config, OpUpdateOne, withOIDCSettings(_m))
	return &OIDCSettingsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *OIDCSettingsClient) UpdateOneID(id string) *OIDCSettingsUpdateOne {
	mutation := newOIDCSettingsMutation(c.config, OpUpdateOne, withOIDCSettingsID(id))
	return &OIDCSettingsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for OIDCSettings.
func (c *OIDCSettingsClient) Delete() *OIDCSettingsDelete {
	mutation := newOIDCSettingsMutation(c.config, OpDelete)
	return &OIDCSettingsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *OIDCSettingsClient) DeleteOne(_m *OIDCSettings) *OIDCSettingsDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *OIDCSettingsClient) DeleteOneID(id string) *OIDCSettingsDeleteOne {
	builder := c.Delete().Where(oidcsettings.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &OIDCSettingsDeleteOne{builder}
}

// Query returns a query builder for OIDCSettings.
func (c *OIDCSettingsClient) Query() *OIDCSettingsQuery {
	return &OIDCSettingsQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeOIDCSettings},
		inters: c.Interceptors(),
	}
}

// Get returns a OIDCSettings entity by its id.
func (c *OIDCSettingsClient) Get(ctx context.Context, id string) (*OIDCSettings, error) {
	return c.Query().Where(oidcsettings.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *OIDCSettingsClient) GetX(ctx context.Context, id string) *OIDCSettings {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *OIDCSettingsClient) Hooks() []Hook {
	return c.hooks.OIDCSettings
}

// Interceptors returns the client interceptors.
func (c *OIDCSettingsClient) Interceptors() []Interceptor {
	return c.inters.OIDCSettings
}

func (c *OIDCSettingsClient) mutate(ctx context.Context, m *OIDCSettingsMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&OIDCSettingsCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&OIDCSettingsUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&OIDCSettingsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&OIDCSettingsDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown OIDCSettings mutation op: %q", m.Op())
	}
}

// PasswordPolicyClient is a client for the PasswordPolicy schema.
type PasswordPolicyClient struct {
	config
}

// NewPasswordPolicyClient returns a client for the PasswordPolicy from the given config.
func NewPasswordPolicyClient(c config) *PasswordPolicyClient {
	return &PasswordPolicyClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `passwordpolicy.Hooks(f(g(h())))`.
func (c *PasswordPolicyClient) Use(hooks ...Hook) {
	c.hooks.PasswordPolicy = append(c.hooks.PasswordPolicy, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `passwordpolicy.Intercept(f(g(h())))`.
func (c *PasswordPolicyClient) Intercept(interceptors ...Interceptor) {
	c.inters.PasswordPolicy = append(c.inters.PasswordPolicy, interceptors...)
}

// Create returns a builder for creating a PasswordPolicy entity.
func (c *PasswordPolicyClient) Create() *PasswordPolicyCreate {
	mutation := newPasswordPolicyMutation(c.config, OpCreate)
	return &PasswordPolicyCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of PasswordPolicy entities.
func (c *PasswordPolicyClient) CreateBulk(builders ...*PasswordPolicyCreate) *PasswordPolicyCreateBulk {
	return &PasswordPolicyCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *PasswordPolicyClient) MapCreateBulk(slice any, setFunc func(*PasswordPolicyCreate, int)) *PasswordPolicyCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &PasswordPolicyCreateBulk{err: fmt.Errorf("calling to PasswordPolicyClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*PasswordPolicyCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &PasswordPolicyCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for PasswordPolicy.
func (c *PasswordPolicyClient) Update() *PasswordPolicyUpdate {
	mutation := newPasswordPolicyMutation(c.config, OpUpdate)
	return &PasswordPolicyUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *PasswordPolicyClient) UpdateOne(_m *PasswordPolicy) *PasswordPolicyUpdateOne {
	mutation := newPasswordPolicyMutation(c.config, OpUpdateOne, withPasswordPolicy(_m))
	return &PasswordPolicyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *PasswordPolicyClient) UpdateOneID(id string) *PasswordPolicyUpdateOne {
	mutation := newPasswordPolicyMutation(c.config, OpUpdateOne, withPasswordPolicyID(id))
	return &PasswordPolicyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for PasswordPolicy.
func (c *PasswordPolicyClient) Delete() *PasswordPolicyDelete {
	mutation := newPasswordPolicyMutation(c.config, OpDelete)
	return &PasswordPolicyDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *PasswordPolicyClient) DeleteOne(_m *PasswordPolicy) *PasswordPolicyDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *PasswordPolicyClient) DeleteOneID(id string) *PasswordPolicyDeleteOne {
	builder := c.Delete().Where(passwordpolicy.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &PasswordPolicyDeleteOne{builder}
}

// Query returns a query builder for PasswordPolicy.
func (c *PasswordPolicyClient) Query() *PasswordPolicyQuery {
	return &PasswordPolicyQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypePasswordPolicy},
		inters: c.Interceptors(),
	}
}

// Get returns a PasswordPolicy entity by its id.
func (c *PasswordPolicyClient) Get(ctx context.Context, id string) (*PasswordPolicy, error) {
	return c.Query().Where(passwordpolicy.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *PasswordPolicyClient) GetX(ctx context.Context, id string) *PasswordPolicy {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *PasswordPolicyClient) Hooks() []Hook {
	return c.hooks.PasswordPolicy
}

// Interceptors returns the client interceptors.
func (c *PasswordPolicyClient) Interceptors() []Interceptor {
	return c.inters.PasswordPolicy
}

func (c *PasswordPolicyClient) mutate(ctx context.Context, m *PasswordPolicyMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&PasswordPolicyCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&PasswordPolicyUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&PasswordPolicyUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&PasswordPolicyDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown PasswordPolicy mutation op: %q", m.Op())
	}
}

// RateLimitSettingsClient is a client for the RateLimitSettings schema.
type RateLimitSettingsClient struct {
	config
}

// NewRateLimitSettingsClient returns a client for the RateLimitSettings from the given config.
func NewRateLimitSettingsClient(c config) *RateLimitSettingsClient {
	return &RateLimitSettingsClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `ratelimitsettings.Hooks(f(g(h())))`.
func (c *RateLimitSettingsClient) Use(hooks ...Hook) {
	c.hooks.RateLimitSettings = append(c.hooks.RateLimitSettings, hooks...)
}

// Intercept adds a list of query interceptors to the interceptors stack.
// A call to `Intercept(f, g, h)` equals to `ratelimitsettings.Intercept(f(g(h())))`.
func (c *RateLimitSettingsClient) Intercept(interceptors ...Interceptor) {
	c.inters.RateLimitSettings = append(c.inters.RateLimitSettings, interceptors...)
}

// Create returns a builder for creating a RateLimitSettings entity.
func (c *RateLimitSettingsClient) Create() *RateLimitSettingsCreate {
	mutation := newRateLimitSettingsMutation(c.config, OpCreate)
	return &RateLimitSettingsCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of RateLimitSettings entities.
func (c *RateLimitSettingsClient) CreateBulk(builders ...*RateLimitSettingsCreate) *RateLimitSettingsCreateBulk {
	return &RateLimitSettingsCreateBulk{config: c.config, builders: builders}
}

// MapCreateBulk creates a bulk creation builder from the given slice. For each item in the slice, the function creates
// a builder and applies setFunc on it.
func (c *RateLimitSettingsClient) MapCreateBulk(slice any, setFunc func(*RateLimitSettingsCreate, int)) *RateLimitSettingsCreateBulk {
	rv := reflect.ValueOf(slice)
	if rv.Kind() != reflect.Slice {
		return &RateLimitSettingsCreateBulk{err: fmt.Errorf("calling to RateLimitSettingsClient.MapCreateBulk with wrong type %T, need slice", slice)}
	}
	builders := make([]*RateLimitSettingsCreate, rv.Len())
	for i := 0; i < rv.Len(); i++ {
		builders[i] = c.Create()
		setFunc(builders[i], i)
	}
	return &RateLimitSettingsCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for RateLimitSettings.
func (c *RateLimitSettingsClient) Update() *RateLimitSettingsUpdate {
	mutation := newRateLimitSettingsMutation(c.config, OpUpdate)
	return &RateLimitSettingsUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *RateLimitSettingsClient) UpdateOne(_m *RateLimitSettings) *RateLimitSettingsUpdateOne {
	mutation := newRateLimitSettingsMutation(c.config, OpUpdateOne, withRateLimitSettings(_m))
	return &RateLimitSettingsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *RateLimitSettingsClient) UpdateOneID(id string) *RateLimitSettingsUpdateOne {
	mutation := newRateLimitSettingsMutation(c.config, OpUpdateOne, withRateLimitSettingsID(id))
	return &RateLimitSettingsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for RateLimitSettings.
func (c *RateLimitSettingsClient) Delete() *RateLimitSettingsDelete {
	mutation := newRateLimitSettingsMutation(c.config, OpDelete)
	return &RateLimitSettingsDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a builder for deleting the given entity.
func (c *RateLimitSettingsClient) DeleteOne(_m *RateLimitSettings) *RateLimitSettingsDeleteOne {
	return c.DeleteOneID(_m.ID)
}

// DeleteOneID returns a builder for deleting the given entity by its id.
func (c *RateLimitSettingsClient) DeleteOneID(id string) *RateLimitSettingsDeleteOne {
	builder := c.Delete().Where(ratelimitsettings.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &RateLimitSettingsDeleteOne{builder}
}

// Query returns a query builder for RateLimitSettings.
func (c *RateLimitSettingsClient) Query() *RateLimitSettingsQuery {
	return &RateLimitSettingsQuery{
		config: c.config,
		ctx:    &QueryContext{Type: TypeRateLimitSettings},
		inters: c.Interceptors(),
	}
}

// Get returns a RateLimitSettings entity by its id.
func (c *RateLimitSettingsClient) Get(ctx context.Context, id string) (*RateLimitSettings, error) {
	return c.Query().Where(ratelimitsettings.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *RateLimitSettingsClient) GetX(ctx context.Context, id string) *RateLimitSettings {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *RateLimitSettingsClient) Hooks() []Hook {
	return c.hooks.RateLimitSettings
}

// Interceptors returns the client interceptors.
func (c *RateLimitSettingsClient) Interceptors() []Interceptor {
	return c.inters.RateLimitSettings
}

func (c *RateLimitSettingsClient) mutate(ctx context.Context, m *RateLimitSettingsMutation) (Value, error) {
	switch m.Op() {
	case OpCreate:
		return (&RateLimitSettingsCreate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdate:
		return (&RateLimitSettingsUpdate{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpUpdateOne:
		return (&RateLimitSettingsUpdateOne{config: c.config, hooks: c.Hooks(), mutation: m}).Save(ctx)
	case OpDelete, OpDeleteOne:
		return (&RateLimitSettingsDelete{config: c.config, hooks: c.Hooks(), mutation: m}).Exec(ctx)
	default:
		return nil, fmt.Errorf("ent: unknown RateLimitSettings mutation op: %q", m.Op())
	}
}

// hooks and interceptors per client, for fast access.
type (
	hooks struct {
		BrandingSettings, OIDCSettings, PasswordPolicy, RateLimitSettings []ent.Hook
	}
	inters struct {
		BrandingSettings, OIDCSettings, PasswordPolicy,
		RateLimitSettings []ent.Interceptor
	}
)
