// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/andersonlmarchi/client-manager/services/configuration/ent/oidcsettings"
)

// OIDCSettings is the model entity for the OIDCSettings schema.
type OIDCSettings struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Issuer holds the value of the "issuer" field.
	Issuer string `json:"issuer,omitempty"`
	// AccessTokenTTLSeconds holds the value of the "access_token_ttl_seconds" field.
	AccessTokenTTLSeconds int `json:"access_token_ttl_seconds,omitempty"`
	// RefreshTokenTTLSeconds holds the value of the "refresh_token_ttl_seconds" field.
	RefreshTokenTTLSeconds int `json:"refresh_token_ttl_seconds,omitempty"`
	// IDTokenTTLSeconds holds the value of the "id_token_ttl_seconds" field.
	IDTokenTTLSeconds int `json:"id_token_ttl_seconds,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OIDCSettings) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case oidcsettings.FieldAccessTokenTTLSeconds, oidcsettings.FieldRefreshTokenTTLSeconds, oidcsettings.FieldIDTokenTTLSeconds:
			values[i] = new(sql.NullInt64)
		case oidcsettings.FieldID, oidcsettings.FieldIssuer:
			values[i] = new(sql.NullString)
		case oidcsettings.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OIDCSettings fields.
func (_m *OIDCSettings) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case oidcsettings.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case oidcsettings.FieldIssuer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field issuer", values[i])
			} else if value.Valid {
				_m.Issuer = value.String
			}
		case oidcsettings.FieldAccessTokenTTLSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field access_token_ttl_seconds", values[i])
			} else if value.Valid {
				_m.AccessTokenTTLSeconds = int(value.Int64)
			}
		case oidcsettings.FieldRefreshTokenTTLSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field refresh_token_ttl_seconds", values[i])
			} else if value.Valid {
				_m.RefreshTokenTTLSeconds = int(value.Int64)
			}
		case oidcsettings.FieldIDTokenTTLSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field id_token_ttl_seconds", values[i])
			} else if value.Valid {
				_m.IDTokenTTLSeconds = int(value.Int64)
			}
		case oidcsettings.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OIDCSettings.
// This includes values selected through modifiers, order, etc.
func (_m *OIDCSettings) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this OIDCSettings.
// Note that you need to call OIDCSettings.Unwrap() before calling this method if this OIDCSettings
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OIDCSettings) Update() *OIDCSettingsUpdateOne {
	return NewOIDCSettingsClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OIDCSettings entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OIDCSettings) Unwrap() *OIDCSettings {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OIDCSettings is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OIDCSettings) String() string {
	var builder strings.Builder
	builder.WriteString("OIDCSettings(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("issuer=")
	builder.WriteString(_m.Issuer)
	builder.WriteString(", ")
	builder.WriteString("access_token_ttl_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccessTokenTTLSeconds))
	builder.WriteString(", ")
	builder.WriteString("refresh_token_ttl_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.RefreshTokenTTLSeconds))
	builder.WriteString(", ")
	builder.WriteString("id_token_ttl_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.IDTokenTTLSeconds))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OIDCSettingsSlice is a parsable slice of OIDCSettings.
type OIDCSettingsSlice []*OIDCSettings
