// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/andersonlmarchi/client-manager/services/configuration/ent/oidcsettings"
	"github.com/andersonlmarchi/client-manager/services/configuration/ent/predicate"
)

// OIDCSettingsDelete is the builder for deleting a OIDCSettings entity.
type OIDCSettingsDelete struct {
	config
	hooks    []Hook
	mutation *OIDCSettingsMutation
}

// Where appends a list predicates to the OIDCSettingsDelete builder.
func (_d *OIDCSettingsDelete) Where(ps ...predicate.OIDCSettings) *OIDCSettingsDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OIDCSettingsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OIDCSettingsDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OIDCSettingsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(oidcsettings.Table, sqlgraph.NewFieldSpec(oidcsettings.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OIDCSettingsDeleteOne is the builder for deleting a single OIDCSettings entity.
type OIDCSettingsDeleteOne struct {
	_d *OIDCSettingsDelete
}

// Where appends a list predicates to the OIDCSettingsDelete builder.
func (_d *OIDCSettingsDeleteOne) Where(ps ...predicate.OIDCSettings) *OIDCSettingsDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OIDCSettingsDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{oidcsettings.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OIDCSettingsDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
