// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/andersonlmarchi/client-manager/services/configuration/ent/oidcsettings"
	"github.com/andersonlmarchi/client-manager/services/configuration/ent/predicate"
)

// OIDCSettingsUpdate is the builder for updating OIDCSettings entities.
type OIDCSettingsUpdate struct {
	config
	hooks    []Hook
	mutation *OIDCSettingsMutation
}

// Where appends a list predicates to the OIDCSettingsUpdate builder.
func (_u *OIDCSettingsUpdate) Where(ps ...predicate.OIDCSettings) *OIDCSettingsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetIssuer sets the "issuer" field.
func (_u *OIDCSettingsUpdate) SetIssuer(v string) *OIDCSettingsUpdate {
	_u.mutation.SetIssuer(v)
	return _u
}

// SetNillableIssuer sets the "issuer" field if the given value is not nil.
func (_u *OIDCSettingsUpdate) SetNillableIssuer(v *string) *OIDCSettingsUpdate {
	if v != nil {
		_u.SetIssuer(*v)
	}
	return _u
}

// SetAccessTokenTTLSeconds sets the "access_token_ttl_seconds" field.
func (_u *OIDCSettingsUpdate) SetAccessTokenTTLSeconds(v int) *OIDCSettingsUpdate {
	_u.mutation.ResetAccessTokenTTLSeconds()
	_u.mutation.SetAccessTokenTTLSeconds(v)
	return _u
}

// SetNillableAccessTokenTTLSeconds sets the "access_token_ttl_seconds" field if the given value is not nil.
func (_u *OIDCSettingsUpdate) SetNillableAccessTokenTTLSeconds(v *int) *OIDCSettingsUpdate {
	if v != nil {
		_u.SetAccessTokenTTLSeconds(*v)
	}
	return _u
}

// AddAccessTokenTTLSeconds adds value to the "access_token_ttl_seconds" field.
func (_u *OIDCSettingsUpdate) AddAccessTokenTTLSeconds(v int) *OIDCSettingsUpdate {
	_u.mutation.AddAccessTokenTTLSeconds(v)
	return _u
}

// SetRefreshTokenTTLSeconds sets the "refresh_token_ttl_seconds" field.
func (_u *OIDCSettingsUpdate) SetRefreshTokenTTLSeconds(v int) *OIDCSettingsUpdate {
	_u.mutation.ResetRefreshTokenTTLSeconds()
	_u.mutation.SetRefreshTokenTTLSeconds(v)
	return _u
}

// SetNillableRefreshTokenTTLSeconds sets the "refresh_token_ttl_seconds" field if the given value is not nil.
func (_u *OIDCSettingsUpdate) SetNillableRefreshTokenTTLSeconds(v *int) *OIDCSettingsUpdate {
	if v != nil {
		_u.SetRefreshTokenTTLSeconds(*v)
	}
	return _u
}

// AddRefreshTokenTTLSeconds adds value to the "refresh_token_ttl_seconds" field.
func (_u *OIDCSettingsUpdate) AddRefreshTokenTTLSeconds(v int) *OIDCSettingsUpdate {
	_u.mutation.AddRefreshTokenTTLSeconds(v)
	return _u
}

// SetIDTokenTTLSeconds sets the "id_token_ttl_seconds" field.
func (_u *OIDCSettingsUpdate) SetIDTokenTTLSeconds(v int) *OIDCSettingsUpdate {
	_u.mutation.ResetIDTokenTTLSeconds()
	_u.mutation.SetIDTokenTTLSeconds(v)
	return _u
}

// SetNillableIDTokenTTLSeconds sets the "id_token_ttl_seconds" field if the given value is not nil.
func (_u *OIDCSettingsUpdate) SetNillableIDTokenTTLSeconds(v *int) *OIDCSettingsUpdate {
	if v != nil {
		_u.SetIDTokenTTLSeconds(*v)
	}
	return _u
}

// AddIDTokenTTLSeconds adds value to the "id_token_ttl_seconds" field.
func (_u *OIDCSettingsUpdate) AddIDTokenTTLSeconds(v int) *OIDCSettingsUpdate {
	_u.mutation.AddIDTokenTTLSeconds(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OIDCSettingsUpdate) SetUpdatedAt(v time.Time) *OIDCSettingsUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OIDCSettingsMutation object of the builder.
func (_u *OIDCSettingsUpdate) Mutation() *OIDCSettingsMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OIDCSettingsUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OIDCSettingsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OIDCSettingsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OIDCSettingsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OIDCSettingsUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oidcsettings.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OIDCSettingsUpdate) check() error {
	if v, ok := _u.mutation.Issuer(); ok {
		if err := oidcsettings.IssuerValidator(v); err != nil {
			return &ValidationError{Name: "issuer", err: fmt.Errorf(`ent: validator failed for field "OIDCSettings.issuer": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccessTokenTTLSeconds(); ok {
		if err := oidcsettings.AccessTokenTTLSecondsValidator(v); err != nil {
			return &ValidationError{Name: "access_token_ttl_seconds", err: fmt.Errorf(`ent: validator failed for field "OIDCSettings.access_token_ttl_seconds": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RefreshTokenTTLSeconds(); ok {
		if err := oidcsettings.RefreshTokenTTLSecondsValidator(v); err != nil {
			return &ValidationError{Name: "refresh_token_ttl_seconds", err: fmt.Errorf(`ent: validator failed for field "OIDCSettings.refresh_token_ttl_seconds": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IDTokenTTLSeconds(); ok {
		if err := oidcsettings.IDTokenTTLSecondsValidator(v); err != nil {
			return &ValidationError{Name: "id_token_ttl_seconds", err: fmt.Errorf(`ent: validator failed for field "OIDCSettings.id_token_ttl_seconds": %w`, err)}
		}
	}
	return nil
}

func (_u *OIDCSettingsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oidcsettings.Table, oidcsettings.Columns, sqlgraph.NewFieldSpec(oidcsettings.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Issuer(); ok {
		_spec.SetField(oidcsettings.FieldIssuer, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessTokenTTLSeconds(); ok {
		_spec.SetField(oidcsettings.FieldAccessTokenTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAccessTokenTTLSeconds(); ok {
		_spec.AddField(oidcsettings.FieldAccessTokenTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RefreshTokenTTLSeconds(); ok {
		_spec.SetField(oidcsettings.FieldRefreshTokenTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRefreshTokenTTLSeconds(); ok {
		_spec.AddField(oidcsettings.FieldRefreshTokenTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IDTokenTTLSeconds(); ok {
		_spec.SetField(oidcsettings.FieldIDTokenTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIDTokenTTLSeconds(); ok {
		_spec.AddField(oidcsettings.FieldIDTokenTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oidcsettings.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oidcsettings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OIDCSettingsUpdateOne is the builder for updating a single OIDCSettings entity.
type OIDCSettingsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OIDCSettingsMutation
}

// SetIssuer sets the "issuer" field.
func (_u *OIDCSettingsUpdateOne) SetIssuer(v string) *OIDCSettingsUpdateOne {
	_u.mutation.SetIssuer(v)
	return _u
}

// SetNillableIssuer sets the "issuer" field if the given value is not nil.
func (_u *OIDCSettingsUpdateOne) SetNillableIssuer(v *string) *OIDCSettingsUpdateOne {
	if v != nil {
		_u.SetIssuer(*v)
	}
	return _u
}

// SetAccessTokenTTLSeconds sets the "access_token_ttl_seconds" field.
func (_u *OIDCSettingsUpdateOne) SetAccessTokenTTLSeconds(v int) *OIDCSettingsUpdateOne {
	_u.mutation.ResetAccessTokenTTLSeconds()
	_u.mutation.SetAccessTokenTTLSeconds(v)
	return _u
}

// SetNillableAccessTokenTTLSeconds sets the "access_token_ttl_seconds" field if the given value is not nil.
func (_u *OIDCSettingsUpdateOne) SetNillableAccessTokenTTLSeconds(v *int) *OIDCSettingsUpdateOne {
	if v != nil {
		_u.SetAccessTokenTTLSeconds(*v)
	}
	return _u
}

// AddAccessTokenTTLSeconds adds value to the "access_token_ttl_seconds" field.
func (_u *OIDCSettingsUpdateOne) AddAccessTokenTTLSeconds(v int) *OIDCSettingsUpdateOne {
	_u.mutation.AddAccessTokenTTLSeconds(v)
	return _u
}

// SetRefreshTokenTTLSeconds sets the "refresh_token_ttl_seconds" field.
func (_u *OIDCSettingsUpdateOne) SetRefreshTokenTTLSeconds(v int) *OIDCSettingsUpdateOne {
	_u.mutation.ResetRefreshTokenTTLSeconds()
	_u.mutation.SetRefreshTokenTTLSeconds(v)
	return _u
}

// SetNillableRefreshTokenTTLSeconds sets the "refresh_token_ttl_seconds" field if the given value is not nil.
func (_u *OIDCSettingsUpdateOne) SetNillableRefreshTokenTTLSeconds(v *int) *OIDCSettingsUpdateOne {
	if v != nil {
		_u.SetRefreshTokenTTLSeconds(*v)
	}
	return _u
}

// AddRefreshTokenTTLSeconds adds value to the "refresh_token_ttl_seconds" field.
func (_u *OIDCSettingsUpdateOne) AddRefreshTokenTTLSeconds(v int) *OIDCSettingsUpdateOne {
	_u.mutation.AddRefreshTokenTTLSeconds(v)
	return _u
}

// SetIDTokenTTLSeconds sets the "id_token_ttl_seconds" field.
func (_u *OIDCSettingsUpdateOne) SetIDTokenTTLSeconds(v int) *OIDCSettingsUpdateOne {
	_u.mutation.ResetIDTokenTTLSeconds()
	_u.mutation.SetIDTokenTTLSeconds(v)
	return _u
}

// SetNillableIDTokenTTLSeconds sets the "id_token_ttl_seconds" field if the given value is not nil.
func (_u *OIDCSettingsUpdateOne) SetNillableIDTokenTTLSeconds(v *int) *OIDCSettingsUpdateOne {
	if v != nil {
		_u.SetIDTokenTTLSeconds(*v)
	}
	return _u
}

// AddIDTokenTTLSeconds adds value to the "id_token_ttl_seconds" field.
func (_u *OIDCSettingsUpdateOne) AddIDTokenTTLSeconds(v int) *OIDCSettingsUpdateOne {
	_u.mutation.AddIDTokenTTLSeconds(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OIDCSettingsUpdateOne) SetUpdatedAt(v time.Time) *OIDCSettingsUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the OIDCSettingsMutation object of the builder.
func (_u *OIDCSettingsUpdateOne) Mutation() *OIDCSettingsMutation {
	return _u.mutation
}

// Where appends a list predicates to the OIDCSettingsUpdate builder.
func (_u *OIDCSettingsUpdateOne) Where(ps ...predicate.OIDCSettings) *OIDCSettingsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OIDCSettingsUpdateOne) Select(field string, fields ...string) *OIDCSettingsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OIDCSettings entity.
func (_u *OIDCSettingsUpdateOne) Save(ctx context.Context) (*OIDCSettings, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OIDCSettingsUpdateOne) SaveX(ctx context.Context) *OIDCSettings {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OIDCSettingsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OIDCSettingsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OIDCSettingsUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oidcsettings.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OIDCSettingsUpdateOne) check() error {
	if v, ok := _u.mutation.Issuer(); ok {
		if err := oidcsettings.IssuerValidator(v); err != nil {
			return &ValidationError{Name: "issuer", err: fmt.Errorf(`ent: validator failed for field "OIDCSettings.issuer": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccessTokenTTLSeconds(); ok {
		if err := oidcsettings.AccessTokenTTLSecondsValidator(v); err != nil {
			return &ValidationError{Name: "access_token_ttl_seconds", err: fmt.Errorf(`ent: validator failed for field "OIDCSettings.access_token_ttl_seconds": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RefreshTokenTTLSeconds(); ok {
		if err := oidcsettings.RefreshTokenTTLSecondsValidator(v); err != nil {
			return &ValidationError{Name: "refresh_token_ttl_seconds", err: fmt.Errorf(`ent: validator failed for field "OIDCSettings.refresh_token_ttl_seconds": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IDTokenTTLSeconds(); ok {
		if err := oidcsettings.IDTokenTTLSecondsValidator(v); err != nil {
			return &ValidationError{Name: "id_token_ttl_seconds", err: fmt.Errorf(`ent: validator failed for field "OIDCSettings.id_token_ttl_seconds": %w`, err)}
		}
	}
	return nil
}

func (_u *OIDCSettingsUpdateOne) sqlSave(ctx context.Context) (_node *OIDCSettings, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oidcsettings.Table, oidcsettings.Columns, sqlgraph.NewFieldSpec(oidcsettings.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OIDCSettings.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oidcsettings.FieldID)
		for _, f := range fields {
			if !oidcsettings.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oidcsettings.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Issuer(); ok {
		_spec.SetField(oidcsettings.FieldIssuer, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccessTokenTTLSeconds(); ok {
		_spec.SetField(oidcsettings.FieldAccessTokenTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAccessTokenTTLSeconds(); ok {
		_spec.AddField(oidcsettings.FieldAccessTokenTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RefreshTokenTTLSeconds(); ok {
		_spec.SetField(oidcsettings.FieldRefreshTokenTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedRefreshTokenTTLSeconds(); ok {
		_spec.AddField(oidcsettings.FieldRefreshTokenTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IDTokenTTLSeconds(); ok {
		_spec.SetField(oidcsettings.FieldIDTokenTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIDTokenTTLSeconds(); ok {
		_spec.AddField(oidcsettings.FieldIDTokenTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oidcsettings.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &OIDCSettings{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oidcsettings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
