// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/andersonlmarchi/client-manager/services/configuration/ent/passwordpolicy"
)

// PasswordPolicy is the model entity for the PasswordPolicy schema.
type PasswordPolicy struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// MinLength holds the value of the "min_length" field.
	MinLength int `json:"min_length,omitempty"`
	// RequireUpper holds the value of the "require_upper" field.
	RequireUpper bool `json:"require_upper,omitempty"`
	// RequireLower holds the value of the "require_lower" field.
	RequireLower bool `json:"require_lower,omitempty"`
	// RequireNumber holds the value of the "require_number" field.
	RequireNumber bool `json:"require_number,omitempty"`
	// RequireSymbol holds the value of the "require_symbol" field.
	RequireSymbol bool `json:"require_symbol,omitempty"`
	// MaxAgeDays holds the value of the "max_age_days" field.
	MaxAgeDays int `json:"max_age_days,omitempty"`
	// HistoryCount holds the value of the "history_count" field.
	HistoryCount int `json:"history_count,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PasswordPolicy) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case passwordpolicy.FieldRequireUpper, passwordpolicy.FieldRequireLower, passwordpolicy.FieldRequireNumber, passwordpolicy.FieldRequireSymbol:
			values[i] = new(sql.NullBool)
		case passwordpolicy.FieldMinLength, passwordpolicy.FieldMaxAgeDays, passwordpolicy.FieldHistoryCount:
			values[i] = new(sql.NullInt64)
		case passwordpolicy.FieldID:
			values[i] = new(sql.NullString)
		case passwordpolicy.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PasswordPolicy fields.
func (_m *PasswordPolicy) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case passwordpolicy.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case passwordpolicy.FieldMinLength:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field min_length", values[i])
			} else if value.Valid {
				_m.MinLength = int(value.Int64)
			}
		case passwordpolicy.FieldRequireUpper:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field require_upper", values[i])
			} else if value.Valid {
				_m.RequireUpper = value.Bool
			}
		case passwordpolicy.FieldRequireLower:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field require_lower", values[i])
			} else if value.Valid {
				_m.RequireLower = value.Bool
			}
		case passwordpolicy.FieldRequireNumber:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field require_number", values[i])
			} else if value.Valid {
				_m.RequireNumber = value.Bool
			}
		case passwordpolicy.FieldRequireSymbol:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field require_symbol", values[i])
			} else if value.Valid {
				_m.RequireSymbol = value.Bool
			}
		case passwordpolicy.FieldMaxAgeDays:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_age_days", values[i])
			} else if value.Valid {
				_m.MaxAgeDays = int(value.Int64)
			}
		case passwordpolicy.FieldHistoryCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field history_count", values[i])
			} else if value.Valid {
				_m.HistoryCount = int(value.Int64)
			}
		case passwordpolicy.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PasswordPolicy.
// This includes values selected through modifiers, order, etc.
func (_m *PasswordPolicy) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PasswordPolicy.
// Note that you need to call PasswordPolicy.Unwrap() before calling this method if this PasswordPolicy
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PasswordPolicy) Update() *PasswordPolicyUpdateOne {
	return NewPasswordPolicyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PasswordPolicy entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PasswordPolicy) Unwrap() *PasswordPolicy {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PasswordPolicy is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PasswordPolicy) String() string {
	var builder strings.Builder
	builder.WriteString("PasswordPolicy(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("min_length=")
	builder.WriteString(fmt.Sprintf("%v", _m.MinLength))
	builder.WriteString(", ")
	builder.WriteString("require_upper=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequireUpper))
	builder.WriteString(", ")
	builder.WriteString("require_lower=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequireLower))
	builder.WriteString(", ")
	builder.WriteString("require_number=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequireNumber))
	builder.WriteString(", ")
	builder.WriteString("require_symbol=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequireSymbol))
	builder.WriteString(", ")
	builder.WriteString("max_age_days=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxAgeDays))
	builder.WriteString(", ")
	builder.WriteString("history_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.HistoryCount))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PasswordPolicies is a parsable slice of PasswordPolicy.
type PasswordPolicies []*PasswordPolicy
