// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/andersonlmarchi/client-manager/services/configuration/ent/passwordpolicy"
	"github.com/andersonlmarchi/client-manager/services/configuration/ent/predicate"
)

// PasswordPolicyUpdate is the builder for updating PasswordPolicy entities.
type PasswordPolicyUpdate struct {
	config
	hooks    []Hook
	mutation *PasswordPolicyMutation
}

// Where appends a list predicates to the PasswordPolicyUpdate builder.
func (_u *PasswordPolicyUpdate) Where(ps ...predicate.PasswordPolicy) *PasswordPolicyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetMinLength sets the "min_length" field.
func (_u *PasswordPolicyUpdate) SetMinLength(v int) *PasswordPolicyUpdate {
	_u.mutation.ResetMinLength()
	_u.mutation.SetMinLength(v)
	return _u
}

// SetNillableMinLength sets the "min_length" field if the given value is not nil.
func (_u *PasswordPolicyUpdate) SetNillableMinLength(v *int) *PasswordPolicyUpdate {
	if v != nil {
		_u.SetMinLength(*v)
	}
	return _u
}

// AddMinLength adds value to the "min_length" field.
func (_u *PasswordPolicyUpdate) AddMinLength(v int) *PasswordPolicyUpdate {
	_u.mutation.AddMinLength(v)
	return _u
}

// SetRequireUpper sets the "require_upper" field.
func (_u *PasswordPolicyUpdate) SetRequireUpper(v bool) *PasswordPolicyUpdate {
	_u.mutation.SetRequireUpper(v)
	return _u
}

// SetNillableRequireUpper sets the "require_upper" field if the given value is not nil.
func (_u *PasswordPolicyUpdate) SetNillableRequireUpper(v *bool) *PasswordPolicyUpdate {
	if v != nil {
		_u.SetRequireUpper(*v)
	}
	return _u
}

// SetRequireLower sets the "require_lower" field.
func (_u *PasswordPolicyUpdate) SetRequireLower(v bool) *PasswordPolicyUpdate {
	_u.mutation.SetRequireLower(v)
	return _u
}

// SetNillableRequireLower sets the "require_lower" field if the given value is not nil.
func (_u *PasswordPolicyUpdate) SetNillableRequireLower(v *bool) *PasswordPolicyUpdate {
	if v != nil {
		_u.SetRequireLower(*v)
	}
	return _u
}

// SetRequireNumber sets the "require_number" field.
func (_u *PasswordPolicyUpdate) SetRequireNumber(v bool) *PasswordPolicyUpdate {
	_u.mutation.SetRequireNumber(v)
	return _u
}

// SetNillableRequireNumber sets the "require_number" field if the given value is not nil.
func (_u *PasswordPolicyUpdate) SetNillableRequireNumber(v *bool) *PasswordPolicyUpdate {
	if v != nil {
		_u.SetRequireNumber(*v)
	}
	return _u
}

// SetRequireSymbol sets the "require_symbol" field.
func (_u *PasswordPolicyUpdate) SetRequireSymbol(v bool) *PasswordPolicyUpdate {
	_u.mutation.SetRequireSymbol(v)
	return _u
}

// SetNillableRequireSymbol sets the "require_symbol" field if the given value is not nil.
func (_u *PasswordPolicyUpdate) SetNillableRequireSymbol(v *bool) *PasswordPolicyUpdate {
	if v != nil {
		_u.SetRequireSymbol(*v)
	}
	return _u
}

// SetMaxAgeDays sets the "max_age_days" field.
func (_u *PasswordPolicyUpdate) SetMaxAgeDays(v int) *PasswordPolicyUpdate {
	_u.mutation.ResetMaxAgeDays()
	_u.mutation.SetMaxAgeDays(v)
	return _u
}

// SetNillableMaxAgeDays sets the "max_age_days" field if the given value is not nil.
func (_u *PasswordPolicyUpdate) SetNillableMaxAgeDays(v *int) *PasswordPolicyUpdate {
	if v != nil {
		_u.SetMaxAgeDays(*v)
	}
	return _u
}

// AddMaxAgeDays adds value to the "max_age_days" field.
func (_u *PasswordPolicyUpdate) AddMaxAgeDays(v int) *PasswordPolicyUpdate {
	_u.mutation.AddMaxAgeDays(v)
	return _u
}

// SetHistoryCount sets the "history_count" field.
func (_u *PasswordPolicyUpdate) SetHistoryCount(v int) *PasswordPolicyUpdate {
	_u.mutation.ResetHistoryCount()
	_u.mutation.SetHistoryCount(v)
	return _u
}

// SetNillableHistoryCount sets the "history_count" field if the given value is not nil.
func (_u *PasswordPolicyUpdate) SetNillableHistoryCount(v *int) *PasswordPolicyUpdate {
	if v != nil {
		_u.SetHistoryCount(*v)
	}
	return _u
}

// AddHistoryCount adds value to the "history_count" field.
func (_u *PasswordPolicyUpdate) AddHistoryCount(v int) *PasswordPolicyUpdate {
	_u.mutation.AddHistoryCount(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PasswordPolicyUpdate) SetUpdatedAt(v time.Time) *PasswordPolicyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PasswordPolicyMutation object of the builder.
func (_u *PasswordPolicyUpdate) Mutation() *PasswordPolicyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PasswordPolicyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PasswordPolicyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PasswordPolicyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PasswordPolicyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PasswordPolicyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := passwordpolicy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PasswordPolicyUpdate) check() error {
	if v, ok := _u.mutation.MinLength(); ok {
		if err := passwordpolicy.MinLengthValidator(v); err != nil {
			return &ValidationError{Name: "min_length", err: fmt.Errorf(`ent: validator failed for field "PasswordPolicy.min_length": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxAgeDays(); ok {
		if err := passwordpolicy.MaxAgeDaysValidator(v); err != nil {
			return &ValidationError{Name: "max_age_days", err: fmt.Errorf(`ent: validator failed for field "PasswordPolicy.max_age_days": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HistoryCount(); ok {
		if err := passwordpolicy.HistoryCountValidator(v); err != nil {
			return &ValidationError{Name: "history_count", err: fmt.Errorf(`ent: validator failed for field "PasswordPolicy.history_count": %w`, err)}
		}
	}
	return nil
}

func (_u *PasswordPolicyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(passwordpolicy.Table, passwordpolicy.Columns, sqlgraph.NewFieldSpec(passwordpolicy.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MinLength(); ok {
		_spec.SetField(passwordpolicy.FieldMinLength, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMinLength(); ok {
		_spec.AddField(passwordpolicy.FieldMinLength, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RequireUpper(); ok {
		_spec.SetField(passwordpolicy.FieldRequireUpper, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RequireLower(); ok {
		_spec.SetField(passwordpolicy.FieldRequireLower, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RequireNumber(); ok {
		_spec.SetField(passwordpolicy.FieldRequireNumber, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RequireSymbol(); ok {
		_spec.SetField(passwordpolicy.FieldRequireSymbol, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MaxAgeDays(); ok {
		_spec.SetField(passwordpolicy.FieldMaxAgeDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxAgeDays(); ok {
		_spec.AddField(passwordpolicy.FieldMaxAgeDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.HistoryCount(); ok {
		_spec.SetField(passwordpolicy.FieldHistoryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHistoryCount(); ok {
		_spec.AddField(passwordpolicy.FieldHistoryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(passwordpolicy.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{passwordpolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PasswordPolicyUpdateOne is the builder for updating a single PasswordPolicy entity.
type PasswordPolicyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PasswordPolicyMutation
}

// SetMinLength sets the "min_length" field.
func (_u *PasswordPolicyUpdateOne) SetMinLength(v int) *PasswordPolicyUpdateOne {
	_u.mutation.ResetMinLength()
	_u.mutation.SetMinLength(v)
	return _u
}

// SetNillableMinLength sets the "min_length" field if the given value is not nil.
func (_u *PasswordPolicyUpdateOne) SetNillableMinLength(v *int) *PasswordPolicyUpdateOne {
	if v != nil {
		_u.SetMinLength(*v)
	}
	return _u
}

// AddMinLength adds value to the "min_length" field.
func (_u *PasswordPolicyUpdateOne) AddMinLength(v int) *PasswordPolicyUpdateOne {
	_u.mutation.AddMinLength(v)
	return _u
}

// SetRequireUpper sets the "require_upper" field.
func (_u *PasswordPolicyUpdateOne) SetRequireUpper(v bool) *PasswordPolicyUpdateOne {
	_u.mutation.SetRequireUpper(v)
	return _u
}

// SetNillableRequireUpper sets the "require_upper" field if the given value is not nil.
func (_u *PasswordPolicyUpdateOne) SetNillableRequireUpper(v *bool) *PasswordPolicyUpdateOne {
	if v != nil {
		_u.SetRequireUpper(*v)
	}
	return _u
}

// SetRequireLower sets the "require_lower" field.
func (_u *PasswordPolicyUpdateOne) SetRequireLower(v bool) *PasswordPolicyUpdateOne {
	_u.mutation.SetRequireLower(v)
	return _u
}

// SetNillableRequireLower sets the "require_lower" field if the given value is not nil.
func (_u *PasswordPolicyUpdateOne) SetNillableRequireLower(v *bool) *PasswordPolicyUpdateOne {
	if v != nil {
		_u.SetRequireLower(*v)
	}
	return _u
}

// SetRequireNumber sets the "require_number" field.
func (_u *PasswordPolicyUpdateOne) SetRequireNumber(v bool) *PasswordPolicyUpdateOne {
	_u.mutation.SetRequireNumber(v)
	return _u
}

// SetNillableRequireNumber sets the "require_number" field if the given value is not nil.
func (_u *PasswordPolicyUpdateOne) SetNillableRequireNumber(v *bool) *PasswordPolicyUpdateOne {
	if v != nil {
		_u.SetRequireNumber(*v)
	}
	return _u
}

// SetRequireSymbol sets the "require_symbol" field.
func (_u *PasswordPolicyUpdateOne) SetRequireSymbol(v bool) *PasswordPolicyUpdateOne {
	_u.mutation.SetRequireSymbol(v)
	return _u
}

// SetNillableRequireSymbol sets the "require_symbol" field if the given value is not nil.
func (_u *PasswordPolicyUpdateOne) SetNillableRequireSymbol(v *bool) *PasswordPolicyUpdateOne {
	if v != nil {
		_u.SetRequireSymbol(*v)
	}
	return _u
}

// SetMaxAgeDays sets the "max_age_days" field.
func (_u *PasswordPolicyUpdateOne) SetMaxAgeDays(v int) *PasswordPolicyUpdateOne {
	_u.mutation.ResetMaxAgeDays()
	_u.mutation.SetMaxAgeDays(v)
	return _u
}

// SetNillableMaxAgeDays sets the "max_age_days" field if the given value is not nil.
func (_u *PasswordPolicyUpdateOne) SetNillableMaxAgeDays(v *int) *PasswordPolicyUpdateOne {
	if v != nil {
		_u.SetMaxAgeDays(*v)
	}
	return _u
}

// AddMaxAgeDays adds value to the "max_age_days" field.
func (_u *PasswordPolicyUpdateOne) AddMaxAgeDays(v int) *PasswordPolicyUpdateOne {
	_u.mutation.AddMaxAgeDays(v)
	return _u
}

// SetHistoryCount sets the "history_count" field.
func (_u *PasswordPolicyUpdateOne) SetHistoryCount(v int) *PasswordPolicyUpdateOne {
	_u.mutation.ResetHistoryCount()
	_u.mutation.SetHistoryCount(v)
	return _u
}

// SetNillableHistoryCount sets the "history_count" field if the given value is not nil.
func (_u *PasswordPolicyUpdateOne) SetNillableHistoryCount(v *int) *PasswordPolicyUpdateOne {
	if v != nil {
		_u.SetHistoryCount(*v)
	}
	return _u
}

// AddHistoryCount adds value to the "history_count" field.
func (_u *PasswordPolicyUpdateOne) AddHistoryCount(v int) *PasswordPolicyUpdateOne {
	_u.mutation.AddHistoryCount(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PasswordPolicyUpdateOne) SetUpdatedAt(v time.Time) *PasswordPolicyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the PasswordPolicyMutation object of the builder.
func (_u *PasswordPolicyUpdateOne) Mutation() *PasswordPolicyMutation {
	return _u.mutation
}

// Where appends a list predicates to the PasswordPolicyUpdate builder.
func (_u *PasswordPolicyUpdateOne) Where(ps ...predicate.PasswordPolicy) *PasswordPolicyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PasswordPolicyUpdateOne) Select(field string, fields ...string) *PasswordPolicyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PasswordPolicy entity.
func (_u *PasswordPolicyUpdateOne) Save(ctx context.Context) (*PasswordPolicy, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PasswordPolicyUpdateOne) SaveX(ctx context.Context) *PasswordPolicy {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PasswordPolicyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PasswordPolicyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PasswordPolicyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := passwordpolicy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PasswordPolicyUpdateOne) check() error {
	if v, ok := _u.mutation.MinLength(); ok {
		if err := passwordpolicy.MinLengthValidator(v); err != nil {
			return &ValidationError{Name: "min_length", err: fmt.Errorf(`ent: validator failed for field "PasswordPolicy.min_length": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MaxAgeDays(); ok {
		if err := passwordpolicy.MaxAgeDaysValidator(v); err != nil {
			return &ValidationError{Name: "max_age_days", err: fmt.Errorf(`ent: validator failed for field "PasswordPolicy.max_age_days": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HistoryCount(); ok {
		if err := passwordpolicy.HistoryCountValidator(v); err != nil {
			return &ValidationError{Name: "history_count", err: fmt.Errorf(`ent: validator failed for field "PasswordPolicy.history_count": %w`, err)}
		}
	}
	return nil
}

func (_u *PasswordPolicyUpdateOne) sqlSave(ctx context.Context) (_node *PasswordPolicy, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(passwordpolicy.Table, passwordpolicy.Columns, sqlgraph.NewFieldSpec(passwordpolicy.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PasswordPolicy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, passwordpolicy.FieldID)
		for _, f := range fields {
			if !passwordpolicy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != passwordpolicy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MinLength(); ok {
		_spec.SetField(passwordpolicy.FieldMinLength, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMinLength(); ok {
		_spec.AddField(passwordpolicy.FieldMinLength, field.TypeInt, value)
	}
	if value, ok := _u.mutation.RequireUpper(); ok {
		_spec.SetField(passwordpolicy.FieldRequireUpper, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RequireLower(); ok {
		_spec.SetField(passwordpolicy.FieldRequireLower, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RequireNumber(); ok {
		_spec.SetField(passwordpolicy.FieldRequireNumber, field.TypeBool, value)
	}
	if value, ok := _u.mutation.RequireSymbol(); ok {
		_spec.SetField(passwordpolicy.FieldRequireSymbol, field.TypeBool, value)
	}
	if value, ok := _u.mutation.MaxAgeDays(); ok {
		_spec.SetField(passwordpolicy.FieldMaxAgeDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxAgeDays(); ok {
		_spec.AddField(passwordpolicy.FieldMaxAgeDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.HistoryCount(); ok {
		_spec.SetField(passwordpolicy.FieldHistoryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHistoryCount(); ok {
		_spec.AddField(passwordpolicy.FieldHistoryCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(passwordpolicy.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &PasswordPolicy{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{passwordpolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
