// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/andersonlmarchi/client-manager/services/configuration/ent/predicate"
	"github.com/andersonlmarchi/client-manager/services/configuration/ent/ratelimitsettings"
)

// RateLimitSettingsUpdate is the builder for updating RateLimitSettings entities.
type RateLimitSettingsUpdate struct {
	config
	hooks    []Hook
	mutation *RateLimitSettingsMutation
}

// Where appends a list predicates to the RateLimitSettingsUpdate builder.
func (_u *RateLimitSettingsUpdate) Where(ps ...predicate.RateLimitSettings) *RateLimitSettingsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDefaultRps sets the "default_rps" field.
func (_u *RateLimitSettingsUpdate) SetDefaultRps(v int) *RateLimitSettingsUpdate {
	_u.mutation.ResetDefaultRps()
	_u.mutation.SetDefaultRps(v)
	return _u
}

// SetNillableDefaultRps sets the "default_rps" field if the given value is not nil.
func (_u *RateLimitSettingsUpdate) SetNillableDefaultRps(v *int) *RateLimitSettingsUpdate {
	if v != nil {
		_u.SetDefaultRps(*v)
	}
	return _u
}

// AddDefaultRps adds value to the "default_rps" field.
func (_u *RateLimitSettingsUpdate) AddDefaultRps(v int) *RateLimitSettingsUpdate {
	_u.mutation.AddDefaultRps(v)
	return _u
}

// SetDefaultBurst sets the "default_burst" field.
func (_u *RateLimitSettingsUpdate) SetDefaultBurst(v int) *RateLimitSettingsUpdate {
	_u.mutation.ResetDefaultBurst()
	_u.mutation.SetDefaultBurst(v)
	return _u
}

// SetNillableDefaultBurst sets the "default_burst" field if the given value is not nil.
func (_u *RateLimitSettingsUpdate) SetNillableDefaultBurst(v *int) *RateLimitSettingsUpdate {
	if v != nil {
		_u.SetDefaultBurst(*v)
	}
	return _u
}

// AddDefaultBurst adds value to the "default_burst" field.
func (_u *RateLimitSettingsUpdate) AddDefaultBurst(v int) *RateLimitSettingsUpdate {
	_u.mutation.AddDefaultBurst(v)
	return _u
}

// SetLoginRps sets the "login_rps" field.
func (_u *RateLimitSettingsUpdate) SetLoginRps(v int) *RateLimitSettingsUpdate {
	_u.mutation.ResetLoginRps()
	_u.mutation.SetLoginRps(v)
	return _u
}

// SetNillableLoginRps sets the "login_rps" field if the given value is not nil.
func (_u *RateLimitSettingsUpdate) SetNillableLoginRps(v *int) *RateLimitSettingsUpdate {
	if v != nil {
		_u.SetLoginRps(*v)
	}
	return _u
}

// AddLoginRps adds value to the "login_rps" field.
func (_u *RateLimitSettingsUpdate) AddLoginRps(v int) *RateLimitSettingsUpdate {
	_u.mutation.AddLoginRps(v)
	return _u
}

// SetLoginBurst sets the "login_burst" field.
func (_u *RateLimitSettingsUpdate) SetLoginBurst(v int) *RateLimitSettingsUpdate {
	_u.mutation.ResetLoginBurst()
	_u.mutation.SetLoginBurst(v)
	return _u
}

// SetNillableLoginBurst sets the "login_burst" field if the given value is not nil.
func (_u *RateLimitSettingsUpdate) SetNillableLoginBurst(v *int) *RateLimitSettingsUpdate {
	if v != nil {
		_u.SetLoginBurst(*v)
	}
	return _u
}

// AddLoginBurst adds value to the "login_burst" field.
func (_u *RateLimitSettingsUpdate) AddLoginBurst(v int) *RateLimitSettingsUpdate {
	_u.mutation.AddLoginBurst(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RateLimitSettingsUpdate) SetUpdatedAt(v time.Time) *RateLimitSettingsUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the RateLimitSettingsMutation object of the builder.
func (_u *RateLimitSettingsUpdate) Mutation() *RateLimitSettingsMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RateLimitSettingsUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RateLimitSettingsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RateLimitSettingsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RateLimitSettingsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RateLimitSettingsUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ratelimitsettings.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RateLimitSettingsUpdate) check() error {
	if v, ok := _u.mutation.DefaultRps(); ok {
		if err := ratelimitsettings.DefaultRpsValidator(v); err != nil {
			return &ValidationError{Name: "default_rps", err: fmt.Errorf(`ent: validator failed for field "RateLimitSettings.default_rps": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultBurst(); ok {
		if err := ratelimitsettings.DefaultBurstValidator(v); err != nil {
			return &ValidationError{Name: "default_burst", err: fmt.Errorf(`ent: validator failed for field "RateLimitSettings.default_burst": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LoginRps(); ok {
		if err := ratelimitsettings.LoginRpsValidator(v); err != nil {
			return &ValidationError{Name: "login_rps", err: fmt.Errorf(`ent: validator failed for field "RateLimitSettings.login_rps": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LoginBurst(); ok {
		if err := ratelimitsettings.LoginBurstValidator(v); err != nil {
			return &ValidationError{Name: "login_burst", err: fmt.Errorf(`ent: validator failed for field "RateLimitSettings.login_burst": %w`, err)}
		}
	}
	return nil
}

func (_u *RateLimitSettingsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ratelimitsettings.Table, ratelimitsettings.Columns, sqlgraph.NewFieldSpec(ratelimitsettings.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DefaultRps(); ok {
		_spec.SetField(ratelimitsettings.FieldDefaultRps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDefaultRps(); ok {
		_spec.AddField(ratelimitsettings.FieldDefaultRps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DefaultBurst(); ok {
		_spec.SetField(ratelimitsettings.FieldDefaultBurst, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDefaultBurst(); ok {
		_spec.AddField(ratelimitsettings.FieldDefaultBurst, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LoginRps(); ok {
		_spec.SetField(ratelimitsettings.FieldLoginRps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLoginRps(); ok {
		_spec.AddField(ratelimitsettings.FieldLoginRps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LoginBurst(); ok {
		_spec.SetField(ratelimitsettings.FieldLoginBurst, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLoginBurst(); ok {
		_spec.AddField(ratelimitsettings.FieldLoginBurst, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ratelimitsettings.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ratelimitsettings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RateLimitSettingsUpdateOne is the builder for updating a single RateLimitSettings entity.
type RateLimitSettingsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RateLimitSettingsMutation
}

// SetDefaultRps sets the "default_rps" field.
func (_u *RateLimitSettingsUpdateOne) SetDefaultRps(v int) *RateLimitSettingsUpdateOne {
	_u.mutation.ResetDefaultRps()
	_u.mutation.SetDefaultRps(v)
	return _u
}

// SetNillableDefaultRps sets the "default_rps" field if the given value is not nil.
func (_u *RateLimitSettingsUpdateOne) SetNillableDefaultRps(v *int) *RateLimitSettingsUpdateOne {
	if v != nil {
		_u.SetDefaultRps(*v)
	}
	return _u
}

// AddDefaultRps adds value to the "default_rps" field.
func (_u *RateLimitSettingsUpdateOne) AddDefaultRps(v int) *RateLimitSettingsUpdateOne {
	_u.mutation.AddDefaultRps(v)
	return _u
}

// SetDefaultBurst sets the "default_burst" field.
func (_u *RateLimitSettingsUpdateOne) SetDefaultBurst(v int) *RateLimitSettingsUpdateOne {
	_u.mutation.ResetDefaultBurst()
	_u.mutation.SetDefaultBurst(v)
	return _u
}

// SetNillableDefaultBurst sets the "default_burst" field if the given value is not nil.
func (_u *RateLimitSettingsUpdateOne) SetNillableDefaultBurst(v *int) *RateLimitSettingsUpdateOne {
	if v != nil {
		_u.SetDefaultBurst(*v)
	}
	return _u
}

// AddDefaultBurst adds value to the "default_burst" field.
func (_u *RateLimitSettingsUpdateOne) AddDefaultBurst(v int) *RateLimitSettingsUpdateOne {
	_u.mutation.AddDefaultBurst(v)
	return _u
}

// SetLoginRps sets the "login_rps" field.
func (_u *RateLimitSettingsUpdateOne) SetLoginRps(v int) *RateLimitSettingsUpdateOne {
	_u.mutation.ResetLoginRps()
	_u.mutation.SetLoginRps(v)
	return _u
}

// SetNillableLoginRps sets the "login_rps" field if the given value is not nil.
func (_u *RateLimitSettingsUpdateOne) SetNillableLoginRps(v *int) *RateLimitSettingsUpdateOne {
	if v != nil {
		_u.SetLoginRps(*v)
	}
	return _u
}

// AddLoginRps adds value to the "login_rps" field.
func (_u *RateLimitSettingsUpdateOne) AddLoginRps(v int) *RateLimitSettingsUpdateOne {
	_u.mutation.AddLoginRps(v)
	return _u
}

// SetLoginBurst sets the "login_burst" field.
func (_u *RateLimitSettingsUpdateOne) SetLoginBurst(v int) *RateLimitSettingsUpdateOne {
	_u.mutation.ResetLoginBurst()
	_u.mutation.SetLoginBurst(v)
	return _u
}

// SetNillableLoginBurst sets the "login_burst" field if the given value is not nil.
func (_u *RateLimitSettingsUpdateOne) SetNillableLoginBurst(v *int) *RateLimitSettingsUpdateOne {
	if v != nil {
		_u.SetLoginBurst(*v)
	}
	return _u
}

// AddLoginBurst adds value to the "login_burst" field.
func (_u *RateLimitSettingsUpdateOne) AddLoginBurst(v int) *RateLimitSettingsUpdateOne {
	_u.mutation.AddLoginBurst(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RateLimitSettingsUpdateOne) SetUpdatedAt(v time.Time) *RateLimitSettingsUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the RateLimitSettingsMutation object of the builder.
func (_u *RateLimitSettingsUpdateOne) Mutation() *RateLimitSettingsMutation {
	return _u.mutation
}

// Where appends a list predicates to the RateLimitSettingsUpdate builder.
func (_u *RateLimitSettingsUpdateOne) Where(ps ...predicate.RateLimitSettings) *RateLimitSettingsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RateLimitSettingsUpdateOne) Select(field string, fields ...string) *RateLimitSettingsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RateLimitSettings entity.
func (_u *RateLimitSettingsUpdateOne) Save(ctx context.Context) (*RateLimitSettings, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RateLimitSettingsUpdateOne) SaveX(ctx context.Context) *RateLimitSettings {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RateLimitSettingsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RateLimitSettingsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RateLimitSettingsUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := ratelimitsettings.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RateLimitSettingsUpdateOne) check() error {
	if v, ok := _u.mutation.DefaultRps(); ok {
		if err := ratelimitsettings.DefaultRpsValidator(v); err != nil {
			return &ValidationError{Name: "default_rps", err: fmt.Errorf(`ent: validator failed for field "RateLimitSettings.default_rps": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DefaultBurst(); ok {
		if err := ratelimitsettings.DefaultBurstValidator(v); err != nil {
			return &ValidationError{Name: "default_burst", err: fmt.Errorf(`ent: validator failed for field "RateLimitSettings.default_burst": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LoginRps(); ok {
		if err := ratelimitsettings.LoginRpsValidator(v); err != nil {
			return &ValidationError{Name: "login_rps", err: fmt.Errorf(`ent: validator failed for field "RateLimitSettings.login_rps": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LoginBurst(); ok {
		if err := ratelimitsettings.LoginBurstValidator(v); err != nil {
			return &ValidationError{Name: "login_burst", err: fmt.Errorf(`ent: validator failed for field "RateLimitSettings.login_burst": %w`, err)}
		}
	}
	return nil
}

func (_u *RateLimitSettingsUpdateOne) sqlSave(ctx context.Context) (_node *RateLimitSettings, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(ratelimitsettings.Table, ratelimitsettings.Columns, sqlgraph.NewFieldSpec(ratelimitsettings.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RateLimitSettings.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, ratelimitsettings.FieldID)
		for _, f := range fields {
			if !ratelimitsettings.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != ratelimitsettings.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DefaultRps(); ok {
		_spec.SetField(ratelimitsettings.FieldDefaultRps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDefaultRps(); ok {
		_spec.AddField(ratelimitsettings.FieldDefaultRps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DefaultBurst(); ok {
		_spec.SetField(ratelimitsettings.FieldDefaultBurst, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDefaultBurst(); ok {
		_spec.AddField(ratelimitsettings.FieldDefaultBurst, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LoginRps(); ok {
		_spec.SetField(ratelimitsettings.FieldLoginRps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLoginRps(); ok {
		_spec.AddField(ratelimitsettings.FieldLoginRps, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LoginBurst(); ok {
		_spec.SetField(ratelimitsettings.FieldLoginBurst, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLoginBurst(); ok {
		_spec.AddField(ratelimitsettings.FieldLoginBurst, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(ratelimitsettings.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &RateLimitSettings{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{ratelimitsettings.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
