// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/andersonlmarchi/client-manager/services/configuration/ent/ratelimitsettings"
)

// RateLimitSettings is the model entity for the RateLimitSettings schema.
type RateLimitSettings struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// DefaultRps holds the value of the "default_rps" field.
	DefaultRps int `json:"default_rps,omitempty"`
	// DefaultBurst holds the value of the "default_burst" field.
	DefaultBurst int `json:"default_burst,omitempty"`
	// LoginRps holds the value of the "login_rps" field.
	LoginRps int `json:"login_rps,omitempty"`
	// LoginBurst holds the value of the "login_burst" field.
	LoginBurst int `json:"login_burst,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RateLimitSettings) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case ratelimitsettings.FieldDefaultRps, ratelimitsettings.FieldDefaultBurst, ratelimitsettings.FieldLoginRps, ratelimitsettings.FieldLoginBurst:
			values[i] = new(sql.NullInt64)
		case ratelimitsettings.FieldID:
			values[i] = new(sql.NullString)
		case ratelimitsettings.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RateLimitSettings fields.
func (_m *RateLimitSettings) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case ratelimitsettings.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case ratelimitsettings.FieldDefaultRps:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field default_rps", values[i])
			} else if value.Valid {
				_m.DefaultRps = int(value.Int64)
			}
		case ratelimitsettings.FieldDefaultBurst:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field default_burst", values[i])
			} else if value.Valid {
				_m.DefaultBurst = int(value.Int64)
			}
		case ratelimitsettings.FieldLoginRps:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field login_rps", values[i])
			} else if value.Valid {
				_m.LoginRps = int(value.Int64)
			}
		case ratelimitsettings.FieldLoginBurst:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field login_burst", values[i])
			} else if value.Valid {
				_m.LoginBurst = int(value.Int64)
			}
		case ratelimitsettings.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RateLimitSettings.
// This includes values selected through modifiers, order, etc.
func (_m *RateLimitSettings) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RateLimitSettings.
// Note that you need to call RateLimitSettings.Unwrap() before calling this method if this RateLimitSettings
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RateLimitSettings) Update() *RateLimitSettingsUpdateOne {
	return NewRateLimitSettingsClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RateLimitSettings entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RateLimitSettings) Unwrap() *RateLimitSettings {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RateLimitSettings is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RateLimitSettings) String() string {
	var builder strings.Builder
	builder.WriteString("RateLimitSettings(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("default_rps=")
	builder.WriteString(fmt.Sprintf("%v", _m.DefaultRps))
	builder.WriteString(", ")
	builder.WriteString("default_burst=")
	builder.WriteString(fmt.Sprintf("%v", _m.DefaultBurst))
	builder.WriteString(", ")
	builder.WriteString("login_rps=")
	builder.WriteString(fmt.Sprintf("%v", _m.LoginRps))
	builder.WriteString(", ")
	builder.WriteString("login_burst=")
	builder.WriteString(fmt.Sprintf("%v", _m.LoginBurst))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RateLimitSettingsSlice is a parsable slice of RateLimitSettings.
type RateLimitSettingsSlice []*RateLimitSettings
