// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/andersonlmarchi/client-manager/services/configuration/ent/brandingsettings"
	"github.com/andersonlmarchi/client-manager/services/configuration/ent/oidcsettings"
	"github.com/andersonlmarchi/client-manager/services/configuration/ent/passwordpolicy"
	"github.com/andersonlmarchi/client-manager/services/configuration/ent/ratelimitsettings"
	"github.com/andersonlmarchi/client-manager/services/configuration/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	brandingsettingsFields := schema.BrandingSettings{}.Fields()
	_ = brandingsettingsFields
	// brandingsettingsDescAppName is the schema descriptor for app_name field.
	brandingsettingsDescAppName := brandingsettingsFields[1].Descriptor()
	// brandingsettings.AppNameValidator is a validator for the "app_name" field. It is called by the builders before save.
	brandingsettings.AppNameValidator = brandingsettingsDescAppName.Validators[0].(func(string) error)
	// brandingsettingsDescUpdatedAt is the schema descriptor for updated_at field.
	brandingsettingsDescUpdatedAt := brandingsettingsFields[9].Descriptor()
	// brandingsettings.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	brandingsettings.DefaultUpdatedAt = brandingsettingsDescUpdatedAt.Default.(func() time.Time)
	// brandingsettings.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	brandingsettings.UpdateDefaultUpdatedAt = brandingsettingsDescUpdatedAt.UpdateDefault.(func() time.Time)
	oidcsettingsFields := schema.OIDCSettings{}.Fields()
	_ = oidcsettingsFields
	// oidcsettingsDescIssuer is the schema descriptor for issuer field.
	oidcsettingsDescIssuer := oidcsettingsFields[1].Descriptor()
	// oidcsettings.IssuerValidator is a validator for the "issuer" field. It is called by the builders before save.
	oidcsettings.IssuerValidator = oidcsettingsDescIssuer.Validators[0].(func(string) error)
	// oidcsettingsDescAccessTokenTTLSeconds is the schema descriptor for access_token_ttl_seconds field.
	oidcsettingsDescAccessTokenTTLSeconds := oidcsettingsFields[2].Descriptor()
	// oidcsettings.DefaultAccessTokenTTLSeconds holds the default value on creation for the access_token_ttl_seconds field.
	oidcsettings.DefaultAccessTokenTTLSeconds = oidcsettingsDescAccessTokenTTLSeconds.Default.(int)
	// oidcsettings.AccessTokenTTLSecondsValidator is a validator for the "access_token_ttl_seconds" field. It is called by the builders before save.
	oidcsettings.AccessTokenTTLSecondsValidator = oidcsettingsDescAccessTokenTTLSeconds.Validators[0].(func(int) error)
	// oidcsettingsDescRefreshTokenTTLSeconds is the schema descriptor for refresh_token_ttl_seconds field.
	oidcsettingsDescRefreshTokenTTLSeconds := oidcsettingsFields[3].Descriptor()
	// oidcsettings.DefaultRefreshTokenTTLSeconds holds the default value on creation for the refresh_token_ttl_seconds field.
	oidcsettings.DefaultRefreshTokenTTLSeconds = oidcsettingsDescRefreshTokenTTLSeconds.Default.(int)
	// oidcsettings.RefreshTokenTTLSecondsValidator is a validator for the "refresh_token_ttl_seconds" field. It is called by the builders before save.
	oidcsettings.RefreshTokenTTLSecondsValidator = oidcsettingsDescRefreshTokenTTLSeconds.Validators[0].(func(int) error)
	// oidcsettingsDescIDTokenTTLSeconds is the schema descriptor for id_token_ttl_seconds field.
	oidcsettingsDescIDTokenTTLSeconds := oidcsettingsFields[4].Descriptor()
	// oidcsettings.DefaultIDTokenTTLSeconds holds the default value on creation for the id_token_ttl_seconds field.
	oidcsettings.DefaultIDTokenTTLSeconds = oidcsettingsDescIDTokenTTLSeconds.Default.(int)
	// oidcsettings.IDTokenTTLSecondsValidator is a validator for the "id_token_ttl_seconds" field. It is called by the builders before save.
	oidcsettings.IDTokenTTLSecondsValidator = oidcsettingsDescIDTokenTTLSeconds.Validators[0].(func(int) error)
	// oidcsettingsDescUpdatedAt is the schema descriptor for updated_at field.
	oidcsettingsDescUpdatedAt := oidcsettingsFields[5].Descriptor()
	// oidcsettings.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	oidcsettings.DefaultUpdatedAt = oidcsettingsDescUpdatedAt.Default.(func() time.Time)
	// oidcsettings.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	oidcsettings.UpdateDefaultUpdatedAt = oidcsettingsDescUpdatedAt.UpdateDefault.(func() time.Time)
	passwordpolicyFields := schema.PasswordPolicy{}.Fields()
	_ = passwordpolicyFields
	// passwordpolicyDescMinLength is the schema descriptor for min_length field.
	passwordpolicyDescMinLength := passwordpolicyFields[1].Descriptor()
	// passwordpolicy.DefaultMinLength holds the default value on creation for the min_length field.
	passwordpolicy.DefaultMinLength = passwordpolicyDescMinLength.Default.(int)
	// passwordpolicy.MinLengthValidator is a validator for the "min_length" field. It is called by the builders before save.
	passwordpolicy.MinLengthValidator = passwordpolicyDescMinLength.Validators[0].(func(int) error)
	// passwordpolicyDescRequireUpper is the schema descriptor for require_upper field.
	passwordpolicyDescRequireUpper := passwordpolicyFields[2].Descriptor()
	// passwordpolicy.DefaultRequireUpper holds the default value on creation for the require_upper field.
	passwordpolicy.DefaultRequireUpper = passwordpolicyDescRequireUpper.Default.(bool)
	// passwordpolicyDescRequireLower is the schema descriptor for require_lower field.
	passwordpolicyDescRequireLower := passwordpolicyFields[3].Descriptor()
	// passwordpolicy.DefaultRequireLower holds the default value on creation for the require_lower field.
	passwordpolicy.DefaultRequireLower = passwordpolicyDescRequireLower.Default.(bool)
	// passwordpolicyDescRequireNumber is the schema descriptor for require_number field.
	passwordpolicyDescRequireNumber := passwordpolicyFields[4].Descriptor()
	// passwordpolicy.DefaultRequireNumber holds the default value on creation for the require_number field.
	passwordpolicy.DefaultRequireNumber = passwordpolicyDescRequireNumber.Default.(bool)
	// passwordpolicyDescRequireSymbol is the schema descriptor for require_symbol field.
	passwordpolicyDescRequireSymbol := passwordpolicyFields[5].Descriptor()
	// passwordpolicy.DefaultRequireSymbol holds the default value on creation for the require_symbol field.
	passwordpolicy.DefaultRequireSymbol = passwordpolicyDescRequireSymbol.Default.(bool)
	// passwordpolicyDescMaxAgeDays is the schema descriptor for max_age_days field.
	passwordpolicyDescMaxAgeDays := passwordpolicyFields[6].Descriptor()
	// passwordpolicy.DefaultMaxAgeDays holds the default value on creation for the max_age_days field.
	passwordpolicy.DefaultMaxAgeDays = passwordpolicyDescMaxAgeDays.Default.(int)
	// passwordpolicy.MaxAgeDaysValidator is a validator for the "max_age_days" field. It is called by the builders before save.
	passwordpolicy.MaxAgeDaysValidator = passwordpolicyDescMaxAgeDays.Validators[0].(func(int) error)
	// passwordpolicyDescHistoryCount is the schema descriptor for history_count field.
	passwordpolicyDescHistoryCount := passwordpolicyFields[7].Descriptor()
	// passwordpolicy.DefaultHistoryCount holds the default value on creation for the history_count field.
	passwordpolicy.DefaultHistoryCount = passwordpolicyDescHistoryCount.Default.(int)
	// passwordpolicy.HistoryCountValidator is a validator for the "history_count" field. It is called by the builders before save.
	passwordpolicy.HistoryCountValidator = passwordpolicyDescHistoryCount.Validators[0].(func(int) error)
	// passwordpolicyDescUpdatedAt is the schema descriptor for updated_at field.
	passwordpolicyDescUpdatedAt := passwordpolicyFields[8].Descriptor()
	// passwordpolicy.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	passwordpolicy.DefaultUpdatedAt = passwordpolicyDescUpdatedAt.Default.(func() time.Time)
	// passwordpolicy.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	passwordpolicy.UpdateDefaultUpdatedAt = passwordpolicyDescUpdatedAt.UpdateDefault.(func() time.Time)
	ratelimitsettingsFields := schema.RateLimitSettings{}.Fields()
	_ = ratelimitsettingsFields
	// ratelimitsettingsDescDefaultRps is the schema descriptor for default_rps field.
	ratelimitsettingsDescDefaultRps := ratelimitsettingsFields[1].Descriptor()
	// ratelimitsettings.DefaultDefaultRps holds the default value on creation for the default_rps field.
	ratelimitsettings.DefaultDefaultRps = ratelimitsettingsDescDefaultRps.Default.(int)
	// ratelimitsettings.DefaultRpsValidator is a validator for the "default_rps" field. It is called by the builders before save.
	ratelimitsettings.DefaultRpsValidator = ratelimitsettingsDescDefaultRps.Validators[0].(func(int) error)
	// ratelimitsettingsDescDefaultBurst is the schema descriptor for default_burst field.
	ratelimitsettingsDescDefaultBurst := ratelimitsettingsFields[2].Descriptor()
	// ratelimitsettings.DefaultDefaultBurst holds the default value on creation for the default_burst field.
	ratelimitsettings.DefaultDefaultBurst = ratelimitsettingsDescDefaultBurst.Default.(int)
	// ratelimitsettings.DefaultBurstValidator is a validator for the "default_burst" field. It is called by the builders before save.
	ratelimitsettings.DefaultBurstValidator = ratelimitsettingsDescDefaultBurst.Validators[0].(func(int) error)
	// ratelimitsettingsDescLoginRps is the schema descriptor for login_rps field.
	ratelimitsettingsDescLoginRps := ratelimitsettingsFields[3].Descriptor()
	// ratelimitsettings.DefaultLoginRps holds the default value on creation for the login_rps field.
	ratelimitsettings.DefaultLoginRps = ratelimitsettingsDescLoginRps.Default.(int)
	// ratelimitsettings.LoginRpsValidator is a validator for the "login_rps" field. It is called by the builders before save.
	ratelimitsettings.LoginRpsValidator = ratelimitsettingsDescLoginRps.Validators[0].(func(int) error)
	// ratelimitsettingsDescLoginBurst is the schema descriptor for login_burst field.
	ratelimitsettingsDescLoginBurst := ratelimitsettingsFields[4].Descriptor()
	// ratelimitsettings.DefaultLoginBurst holds the default value on creation for the login_burst field.
	ratelimitsettings.DefaultLoginBurst = ratelimitsettingsDescLoginBurst.Default.(int)
	// ratelimitsettings.LoginBurstValidator is a validator for the "login_burst" field. It is called by the builders before save.
	ratelimitsettings.LoginBurstValidator = ratelimitsettingsDescLoginBurst.Validators[0].(func(int) error)
	// ratelimitsettingsDescUpdatedAt is the schema descriptor for updated_at field.
	ratelimitsettingsDescUpdatedAt := ratelimitsettingsFields[5].Descriptor()
	// ratelimitsettings.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	ratelimitsettings.DefaultUpdatedAt = ratelimitsettingsDescUpdatedAt.Default.(func() time.Time)
	// ratelimitsettings.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	ratelimitsettings.UpdateDefaultUpdatedAt = ratelimitsettingsDescUpdatedAt.UpdateDefault.(func() time.Time)
}
