// Code generated by ent, DO NOT EDIT.

package ratelimitsettings

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the ratelimitsettings type in the database.
	Label = "rate_limit_settings"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDefaultRps holds the string denoting the default_rps field in the database.
	FieldDefaultRps = "default_rps"
	// FieldDefaultBurst holds the string denoting the default_burst field in the database.
	FieldDefaultBurst = "default_burst"
	// FieldLoginRps holds the string denoting the login_rps field in the database.
	FieldLoginRps = "login_rps"
	// FieldLoginBurst holds the string denoting the login_burst field in the database.
	FieldLoginBurst = "login_burst"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the ratelimitsettings in the database.
	Table = "rate_limit_settings"
)

// Columns holds all SQL columns for ratelimitsettings fields.
var Columns = []string{
	FieldID,
	FieldDefaultRps,
	FieldDefaultBurst,
	FieldLoginRps,
	FieldLoginBurst,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultDefaultRps holds the default value on creation for the "default_rps" field.
	DefaultDefaultRps int
	// DefaultRpsValidator is a validator for the "default_rps" field. It is called by the builders before save.
	DefaultRpsValidator func(int) error
	// DefaultDefaultBurst holds the default value on creation for the "default_burst" field.
	DefaultDefaultBurst int
	// DefaultBurstValidator is a validator for the "default_burst" field. It is called by the builders before save.
	DefaultBurstValidator func(int) error
	// DefaultLoginRps holds the default value on creation for the "login_rps" field.
	DefaultLoginRps int
	// LoginRpsValidator is a validator for the "login_rps" field. It is called by the builders before save.
	LoginRpsValidator func(int) error
	// DefaultLoginBurst holds the default value on creation for the "login_burst" field.
	DefaultLoginBurst int
	// LoginBurstValidator is a validator for the "login_burst" field. It is called by the builders before save.
	LoginBurstValidator func(int) error
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the RateLimitSettings queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDefaultRps orders the results by the default_rps field.
func ByDefaultRps(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDefaultRps, opts...).ToFunc()
}

// ByDefaultBurst orders the results by the default_burst field.
func ByDefaultBurst(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDefaultBurst, opts...).ToFunc()
}

// ByLoginRps orders the results by the login_rps field.
func ByLoginRps(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLoginRps, opts...).ToFunc()
}

// ByLoginBurst orders the results by the login_burst field.
func ByLoginBurst(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLoginBurst, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
