// Code generated by ent, DO NOT EDIT.

package ratelimitsettings

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/andersonlmarchi/client-manager/services/configuration/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldContainsFold(FieldID, id))
}

// DefaultRps applies equality check predicate on the "default_rps" field. It's identical to DefaultRpsEQ.
func DefaultRps(v int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldEQ(FieldDefaultRps, v))
}

// DefaultBurst applies equality check predicate on the "default_burst" field. It's identical to DefaultBurstEQ.
func DefaultBurst(v int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldEQ(FieldDefaultBurst, v))
}

// LoginRps applies equality check predicate on the "login_rps" field. It's identical to LoginRpsEQ.
func LoginRps(v int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldEQ(FieldLoginRps, v))
}

// LoginBurst applies equality check predicate on the "login_burst" field. It's identical to LoginBurstEQ.
func LoginBurst(v int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldEQ(FieldLoginBurst, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldEQ(FieldUpdatedAt, v))
}

// DefaultRpsEQ applies the EQ predicate on the "default_rps" field.
func DefaultRpsEQ(v int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldEQ(FieldDefaultRps, v))
}

// DefaultRpsNEQ applies the NEQ predicate on the "default_rps" field.
func DefaultRpsNEQ(v int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldNEQ(FieldDefaultRps, v))
}

// DefaultRpsIn applies the In predicate on the "default_rps" field.
func DefaultRpsIn(vs ...int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldIn(FieldDefaultRps, vs...))
}

// DefaultRpsNotIn applies the NotIn predicate on the "default_rps" field.
func DefaultRpsNotIn(vs ...int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldNotIn(FieldDefaultRps, vs...))
}

// DefaultRpsGT applies the GT predicate on the "default_rps" field.
func DefaultRpsGT(v int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldGT(FieldDefaultRps, v))
}

// DefaultRpsGTE applies the GTE predicate on the "default_rps" field.
func DefaultRpsGTE(v int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldGTE(FieldDefaultRps, v))
}

// DefaultRpsLT applies the LT predicate on the "default_rps" field.
func DefaultRpsLT(v int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldLT(FieldDefaultRps, v))
}

// DefaultRpsLTE applies the LTE predicate on the "default_rps" field.
func DefaultRpsLTE(v int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldLTE(FieldDefaultRps, v))
}

// DefaultBurstEQ applies the EQ predicate on the "default_burst" field.
func DefaultBurstEQ(v int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldEQ(FieldDefaultBurst, v))
}

// DefaultBurstNEQ applies the NEQ predicate on the "default_burst" field.
func DefaultBurstNEQ(v int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldNEQ(FieldDefaultBurst, v))
}

// DefaultBurstIn applies the In predicate on the "default_burst" field.
func DefaultBurstIn(vs ...int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldIn(FieldDefaultBurst, vs...))
}

// DefaultBurstNotIn applies the NotIn predicate on the "default_burst" field.
func DefaultBurstNotIn(vs ...int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldNotIn(FieldDefaultBurst, vs...))
}

// DefaultBurstGT applies the GT predicate on the "default_burst" field.
func DefaultBurstGT(v int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldGT(FieldDefaultBurst, v))
}

// DefaultBurstGTE applies the GTE predicate on the "default_burst" field.
func DefaultBurstGTE(v int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldGTE(FieldDefaultBurst, v))
}

// DefaultBurstLT applies the LT predicate on the "default_burst" field.
func DefaultBurstLT(v int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldLT(FieldDefaultBurst, v))
}

// DefaultBurstLTE applies the LTE predicate on the "default_burst" field.
func DefaultBurstLTE(v int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldLTE(FieldDefaultBurst, v))
}

// LoginRpsEQ applies the EQ predicate on the "login_rps" field.
func LoginRpsEQ(v int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldEQ(FieldLoginRps, v))
}

// LoginRpsNEQ applies the NEQ predicate on the "login_rps" field.
func LoginRpsNEQ(v int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldNEQ(FieldLoginRps, v))
}

// LoginRpsIn applies the In predicate on the "login_rps" field.
func LoginRpsIn(vs ...int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldIn(FieldLoginRps, vs...))
}

// LoginRpsNotIn applies the NotIn predicate on the "login_rps" field.
func LoginRpsNotIn(vs ...int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldNotIn(FieldLoginRps, vs...))
}

// LoginRpsGT applies the GT predicate on the "login_rps" field.
func LoginRpsGT(v int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldGT(FieldLoginRps, v))
}

// LoginRpsGTE applies the GTE predicate on the "login_rps" field.
func LoginRpsGTE(v int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldGTE(FieldLoginRps, v))
}

// LoginRpsLT applies the LT predicate on the "login_rps" field.
func LoginRpsLT(v int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldLT(FieldLoginRps, v))
}

// LoginRpsLTE applies the LTE predicate on the "login_rps" field.
func LoginRpsLTE(v int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldLTE(FieldLoginRps, v))
}

// LoginBurstEQ applies the EQ predicate on the "login_burst" field.
func LoginBurstEQ(v int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldEQ(FieldLoginBurst, v))
}

// LoginBurstNEQ applies the NEQ predicate on the "login_burst" field.
func LoginBurstNEQ(v int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldNEQ(FieldLoginBurst, v))
}

// LoginBurstIn applies the In predicate on the "login_burst" field.
func LoginBurstIn(vs ...int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldIn(FieldLoginBurst, vs...))
}

// LoginBurstNotIn applies the NotIn predicate on the "login_burst" field.
func LoginBurstNotIn(vs ...int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldNotIn(FieldLoginBurst, vs...))
}

// LoginBurstGT applies the GT predicate on the "login_burst" field.
func LoginBurstGT(v int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldGT(FieldLoginBurst, v))
}

// LoginBurstGTE applies the GTE predicate on the "login_burst" field.
func LoginBurstGTE(v int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldGTE(FieldLoginBurst, v))
}

// LoginBurstLT applies the LT predicate on the "login_burst" field.
func LoginBurstLT(v int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldLT(FieldLoginBurst, v))
}

// LoginBurstLTE applies the LTE predicate on the "login_burst" field.
func LoginBurstLTE(v int) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldLTE(FieldLoginBurst, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RateLimitSettings) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RateLimitSettings) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RateLimitSettings) predicate.RateLimitSettings {
	return predicate.RateLimitSettings(sql.NotPredicates(p))
}
