// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BrandingSettingsColumns holds the columns for the "branding_settings" table.
	BrandingSettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "app_name", Type: field.TypeString},
		{Name: "logo_url", Type: field.TypeString, Nullable: true},
		{Name: "primary_color", Type: field.TypeString, Nullable: true},
		{Name: "support_email", Type: field.TypeString, Nullable: true},
		{Name: "smtp_host_ref", Type: field.TypeString, Nullable: true},
		{Name: "smtp_port_ref", Type: field.TypeString, Nullable: true},
		{Name: "smtp_user_ref", Type: field.TypeString, Nullable: true},
		{Name: "from_email", Type: field.TypeString, Nullable: true},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// BrandingSettingsTable holds the schema information for the "branding_settings" table.
	BrandingSettingsTable = &schema.Table{
		Name:       "branding_settings",
		Columns:    BrandingSettingsColumns,
		PrimaryKey: []*schema.Column{BrandingSettingsColumns[0]},
	}
	// OidcSettingsColumns holds the columns for the "oidc_settings" table.
	OidcSettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "issuer", Type: field.TypeString},
		{Name: "access_token_ttl_seconds", Type: field.TypeInt, Default: 900},
		{Name: "refresh_token_ttl_seconds", Type: field.TypeInt, Default: 2592000},
		{Name: "id_token_ttl_seconds", Type: field.TypeInt, Default: 900},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// OidcSettingsTable holds the schema information for the "oidc_settings" table.
	OidcSettingsTable = &schema.Table{
		Name:       "oidc_settings",
		Columns:    OidcSettingsColumns,
		PrimaryKey: []*schema.Column{OidcSettingsColumns[0]},
	}
	// PasswordPoliciesColumns holds the columns for the "password_policies" table.
	PasswordPoliciesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "min_length", Type: field.TypeInt, Default: 12},
		{Name: "require_upper", Type: field.TypeBool, Default: true},
		{Name: "require_lower", Type: field.TypeBool, Default: true},
		{Name: "require_number", Type: field.TypeBool, Default: true},
		{Name: "require_symbol", Type: field.TypeBool, Default: true},
		{Name: "max_age_days", Type: field.TypeInt, Default: 0},
		{Name: "history_count", Type: field.TypeInt, Default: 0},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// PasswordPoliciesTable holds the schema information for the "password_policies" table.
	PasswordPoliciesTable = &schema.Table{
		Name:       "password_policies",
		Columns:    PasswordPoliciesColumns,
		PrimaryKey: []*schema.Column{PasswordPoliciesColumns[0]},
	}
	// RateLimitSettingsColumns holds the columns for the "rate_limit_settings" table.
	RateLimitSettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "default_rps", Type: field.TypeInt, Default: 60},
		{Name: "default_burst", Type: field.TypeInt, Default: 120},
		{Name: "login_rps", Type: field.TypeInt, Default: 5},
		{Name: "login_burst", Type: field.TypeInt, Default: 10},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// RateLimitSettingsTable holds the schema information for the "rate_limit_settings" table.
	RateLimitSettingsTable = &schema.Table{
		Name:       "rate_limit_settings",
		Columns:    RateLimitSettingsColumns,
		PrimaryKey: []*schema.Column{RateLimitSettingsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BrandingSettingsTable,
		OidcSettingsTable,
		PasswordPoliciesTable,
		RateLimitSettingsTable,
	}
)

func init() {
}
