// Code generated by ent, DO NOT EDIT.

package brandingsettings

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the brandingsettings type in the database.
	Label = "branding_settings"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAppName holds the string denoting the app_name field in the database.
	FieldAppName = "app_name"
	// FieldLogoURL holds the string denoting the logo_url field in the database.
	FieldLogoURL = "logo_url"
	// FieldPrimaryColor holds the string denoting the primary_color field in the database.
	FieldPrimaryColor = "primary_color"
	// FieldSupportEmail holds the string denoting the support_email field in the database.
	FieldSupportEmail = "support_email"
	// FieldSMTPHostRef holds the string denoting the smtp_host_ref field in the database.
	FieldSMTPHostRef = "smtp_host_ref"
	// FieldSMTPPortRef holds the string denoting the smtp_port_ref field in the database.
	FieldSMTPPortRef = "smtp_port_ref"
	// FieldSMTPUserRef holds the string denoting the smtp_user_ref field in the database.
	FieldSMTPUserRef = "smtp_user_ref"
	// FieldFromEmail holds the string denoting the from_email field in the database.
	FieldFromEmail = "from_email"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the brandingsettings in the database.
	Table = "branding_settings"
)

// Columns holds all SQL columns for brandingsettings fields.
var Columns = []string{
	FieldID,
	FieldAppName,
	FieldLogoURL,
	FieldPrimaryColor,
	FieldSupportEmail,
	FieldSMTPHostRef,
	FieldSMTPPortRef,
	FieldSMTPUserRef,
	FieldFromEmail,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AppNameValidator is a validator for the "app_name" field. It is called by the builders before save.
	AppNameValidator func(string) error
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the BrandingSettings queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAppName orders the results by the app_name field.
func ByAppName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAppName, opts...).ToFunc()
}

// ByLogoURL orders the results by the logo_url field.
func ByLogoURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogoURL, opts...).ToFunc()
}

// ByPrimaryColor orders the results by the primary_color field.
func ByPrimaryColor(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrimaryColor, opts...).ToFunc()
}

// BySupportEmail orders the results by the support_email field.
func BySupportEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSupportEmail, opts...).ToFunc()
}

// BySMTPHostRef orders the results by the smtp_host_ref field.
func BySMTPHostRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSMTPHostRef, opts...).ToFunc()
}

// BySMTPPortRef orders the results by the smtp_port_ref field.
func BySMTPPortRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSMTPPortRef, opts...).ToFunc()
}

// BySMTPUserRef orders the results by the smtp_user_ref field.
func BySMTPUserRef(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSMTPUserRef, opts...).ToFunc()
}

// ByFromEmail orders the results by the from_email field.
func ByFromEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromEmail, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
